GluuFederation/flex

admin-ui/plugins/admin/components/Configuration/LicenseDetailsPage.js
https://github.com/GluuFederation/flex/issues/24
=> fix: license validity period should be read only #24

flex-linux-setup/README.md
https://github.com/GluuFederation/flex/issues/28
=> docs: add readme for flex-linux-setup #28

admin-ui/package.json
https://github.com/GluuFederation/flex/issues/32
=> fix: some icons are not visible on admin-ui #32

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/scripts/entrypoint.sh, docker-admin-ui/templates/nginx-default.conf.tmpl
The changeset fixes image build based on new monorepo and required dependencies
=> fix(image): update admin-ui image assets

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-casa/Dockerfile, docker-casa/requirements.txt
Overview:
- update commit hash of admin-ui
- use partial-clone and sparse-checkout to get admin-ui source code
=> chore(image): update dependency

flex-linux-setup/flex_linux_setup/flex_setup.py
Implements `#2` of https://github.com/JanssenProject/jans/issues/855
=> fix: flex-linux-setup update admin-ui plugin url

.github/workflows/central_code_quality_check.yml, casa/pom.xml
Integrating Flex modules with Sonar.
- admin-ui
- casa
- flex-cn-setup
- flex-linux-setup
=> ci: flex integration with Sonar

docker-admin-ui/Dockerfile, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/scripts/entrypoint.sh
Overview:
- update admin-ui source
- move admin-ui directory from /opt/jans/flex to /opt/flex
- disable creation of SSL cert, key, and dhparams
=> chore: update image manifests

admin-ui/app/utils/AppAuthProvider.js
https://github.com/GluuFederation/flex/issues/47
=> fix: use authoriztion_url for authz request #47

admin-ui/plugins/admin/components/CustomScripts/CustomScriptForm.js, admin-ui/plugins/auth-server/components/Configuration/Keys/Jwks/JwkItem.js
https://github.com/GluuFederation/flex/issues/117
=> feat: change in keys page #117

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/plugins/admin/components/CustomScripts/CustomScriptForm.js
https://github.com/GluuFederation/flex/issues/110
=> Admin UI issue 110

docker-admin-ui/Dockerfile, docker-casa/Dockerfile
Overview:
- base image of `gluufederation/casa` is pinned to` liberica-openjre-alpine:11.0.13-8`
- updated casa source
- updated admin-ui source
=> chore: update image dependencies

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/casa_client.ldif, flex-linux-setup/flex_linux_setup/templates/casa_config.ldif, flex-linux-setup/flex_linux_setup/templates/casa_person_authentication_script.ldif
Install Jans Server if not exists and install casa+admin gui
=> feat: flex linux setup casa fix

admin-ui/app/locales/en/translation.json, admin-ui/app/routes/Apps/Gluu/GluuAlert.js, admin-ui/plugins/auth-server/components/Clients/ClientAddPage.js, admin-ui/plugins/auth-server/components/Clients/ClientEditPage.js, admin-ui/plugins/auth-server/redux/reducers/OIDCReducer.js
https://github.com/GluuFederation/flex/issues/129
=> Admin UI issue 129

admin-ui/plugins/auth-server/components/Scopes/ScopeAddPage.js, admin-ui/plugins/auth-server/components/Scopes/ScopeEditPage.js, admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js, admin-ui/plugins/auth-server/redux/reducers/ScopeReducer.js
https://github.com/GluuFederation/flex/issues/140
=> fix:claims dropdown is not populated in Add/Edit scopes page #140

admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js
https://github.com/GluuFederation/flex/issues/144
=> fix: all scopes fields should be saved on add/edit #144

admin-ui/plugins/admin/components/CustomScripts/CustomScriptForm.js, admin-ui/plugins/auth-server/components/Configuration/Defaults/AcrsPage.js
https://github.com/GluuFederation/flex/issues/159
=> fix: default authentication method dropdown is not populating #159

.github/workflows/central_code_quality_check.yml
Code quality check should only run for those modules which has gone through change in respective PR.
Current logic that identifies which module has gone change, is flawed. 
This PR fixes that.
=> ci: fix the change detection logic in Sonar action workflow

docker-admin-ui/Dockerfile, docker-casa/Dockerfile
Overview:
- updated image's LABELs
- sync upstream sources
=> chore: update images

admin-ui/app/routes/Apps/Gluu/GluuCommitDialog.js, admin-ui/app/routes/Apps/Gluu/GluuDialog.js
https://github.com/GluuFederation/flex/issues/165
=> fix: popup message textbox fix

admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
https://github.com/GluuFederation/flex/issues/169
=> fix : prevent enter button

admin-ui/app/utils/PermChecker.js
https://github.com/GluuFederation/flex/issues/175
=> fix: submit button is missing from the Properties page #175

admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js
https://github.com/GluuFederation/flex/issues/178
=> fix: update scope undefined value

admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js
1. Fix Edit Scoped show blank screen
2. Back click also work fine with the Edit screen fix
=> fix(admin-ui): edit scopes blank screen fix

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup version 1.0.1-SNAPSHOT

admin-ui/app/styles/plugins/plugins.css, admin-ui/app/styles/plugins/plugins.scss, admin-ui/package.json
Remove unused `react-big-calendar`
=> fix(admin-ui): remove unused react-big-calendar

admin-ui/app/components/FloatGrid/Grid.js, admin-ui/app/components/Theme/ThemeSelector.js, admin-ui/app/components/Wizard/Wizard.js
Update relative path for styles path
=> feat(admin-ui): Update relative path for styles path

docker-casa/Dockerfile, docker-casa/README.md, docker-casa/conf/prometheus-config.yaml, docker-casa/scripts/entrypoint.sh, flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/auth-server/templates/deployment.yml, flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/casa/templates/deployment.yaml, flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/client-api/templates/deployment.yaml, flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config-api/templates/deployment.yaml, flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config/templates/configmaps.yaml, flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/fido2/templates/deployment.yml, flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/scim/templates/deployment.yml, flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/values.yaml
https://github.com/JanssenProject/jans/issues/682
=> feat: add prometheus jmx

flex-linux-setup/flex_linux_setup/flex_setup.py
As described in https://github.com/GluuFederation/flex/issues/263
=> feat: add fido2-client lib (ref: #263)

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Gluu/GluuFormDetailRow.js, admin-ui/app/routes/Apps/Gluu/GluuRemovableInputRow.js, admin-ui/app/routes/Apps/Gluu/GluuRemovableSelectRow.js, admin-ui/app/routes/Apps/Gluu/GluuRemovableTypeAhead.js, admin-ui/app/routes/Apps/Gluu/GluuTooltip.js, admin-ui/app/utils/AppAuthProvider.js, admin-ui/plugins/user-management/components/UserManagement/UserAddPage.js, admin-ui/plugins/user-management/components/UserManagement/UserClaimEntry.js, admin-ui/plugins/user-management/components/UserManagement/UserDetailViewPage.js, admin-ui/plugins/user-management/components/UserManagement/UserEditPage.js, admin-ui/plugins/user-management/components/UserManagement/UserForm.js
=> admin-ui-issue-94
1. Fix tooltip issue
2. Fix Birthdate show and save
=> fix(admin-ui): tooltip and birthdate fix

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/admin_ui_apache_directive
As described in comment https://github.com/GluuFederation/flex/issues/281#issuecomment-1176107229
=> fix: flex-linux-setup add admin-ui apache directive

admin-ui/app/routes/Apps/Gluu/GluuNotification.js, admin-ui/app/utils/ApiKeyRedirect.js, admin-ui/app/utils/AppAuthProvider.js
https://github.com/GluuFederation/flex/issues/277
=> fix: block user without proper roles #277

admin-ui/plugins/schema/components/Person/AttributeListPage.js
https://github.com/GluuFederation/flex/issues/269
=> fix(admin-ui): fix pattern search

flex-linux-setup/flex_linux_setup/flex_setup.py
As described in https://github.com/GluuFederation/flex/issues/291
=> fix: flex-linux-setup enable apache module mod_dir (ref: #291)

docker-admin-ui/.hadolint.yaml, docker-admin-ui/Dockerfile, docker-admin-ui/Makefile, docker-admin-ui/README.md, docker-admin-ui/scripts/builder.py, docker-admin-ui/scripts/entrypoint.sh
Overview:
- add hadolint (Dockerfile linter) config
- update Makefile rules
- add new env to install admin-ui plugins
=> feat(docker-admin-ui): add support for plugins installation

admin-ui/app/context/theme/config.js, admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Gluu/GluuLabel.js, admin-ui/app/routes/Dashboards/Chart/DashboardChart.js, admin-ui/app/routes/Dashboards/DashboardPage.js, admin-ui/app/routes/Dashboards/DateRange/index.js, admin-ui/app/routes/index.js, admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js, admin-ui/plugins/admin/components/MAU/MauGraph.js
Update styling and missing parts in the new UI
=> feat(admin-ui): new skin update styling and missing part

flex-linux-setup/flex_linux_setup/flex_setup.py
As described in https://github.com/GluuFederation/flex/pull/339
=> feat: flex-linux-setup non-interactive mode

admin-ui/app/routes/Dashboards/DashboardPage.js
Update dashboard count of Actives Users & Access Token Stats dynamically from API
=> feat(admin-ui): update dashboard count of Actives Users & Access Token Stats 

admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js
https://github.com/GluuFederation/flex/issues/334
=> feat: change to Spontaneous Scope should not be allowed #334

admin-ui/plugins/auth-server/components/Clients/ClientAdvancedPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientEncryptionSigningPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
https://github.com/GluuFederation/flex/issues/352
=> fix: mismatch of new added fields name on oidc clients screen #352

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-casa/Dockerfile, docker-casa/requirements.txt
The changeset synchronizes templates and schema from jans-linux-setup and flex-linux-setup as mentioned in #364
=> chore(images): sync templates and schema from upstream

admin-ui/plugins/user-management/redux/reducers/UserReducer.js
https://github.com/GluuFederation/flex/issues/363
=> fix(admin-ui): change password infinity loading fix

admin-ui/plugins/user-management/components/UserManagement/UserForm.js
https://github.com/GluuFederation/flex/issues/363
=> fix(admin-ui): change password payload changed

admin-ui/plugins/user-management/components/UserManagement/UserEditPage.js, admin-ui/plugins/user-management/components/UserManagement/UserForm.js
https://github.com/GluuFederation/flex/issues/367
=> fix(admin-ui):put blank value on removed filed

admin-ui/app/styles/custom/layout.scss, admin-ui/plugins/auth-server/components/Clients/ClientAdvancedPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientListPage.js, admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js, admin-ui/plugins/auth-server/components/Scopes/ScopeListPage.js
https://github.com/GluuFederation/flex/issues/387
=> fix(admin-ui): change link colors

admin-ui/plugins/auth-server/components/Clients/ClientShowSpontaneousScopes.js
https://github.com/GluuFederation/flex/issues/402
=> fix(admin-ui): filter records for spontaneous records

admin-ui/app/components/ThemeSetting/ThemeSettings.js, admin-ui/app/redux/reducers/LogoutReducer.js, admin-ui/app/routes/Apps/Gluu/GluuNavBar.js, admin-ui/app/routes/Apps/Gluu/LanguageMenu.js
Steps: 
1. Log in to admin-ui.
2. Select a different theme and language
3. Log out
4. Re-login
5. The admin-ui again shows default theme and language
Expected:
The admin-ui should remember the theme and language selected last time by user and should set it everytime the user logs in.
=> feat(admin-ui): user lang and theme config for each user

admin-ui/plugins/user-management/common/Constants.js, admin-ui/plugins/user-management/components/UserManagement/UserList.js, admin-ui/plugins/user-management/redux/api/UserApi.js, admin-ui/plugins/user-management/redux/sagas/UserSaga.js
https://github.com/GluuFederation/flex/issues/398
=> feat(admin-ui): implement pattern search in users 

admin-ui/app/components/ThemeSetting/ThemeSettings.js, admin-ui/app/context/theme/themeContext.js, admin-ui/app/redux/reducers/LogoutReducer.js, admin-ui/app/routes/Apps/Gluu/LanguageMenu.js
- User should be able to set language and theme config and even after log out
- User config should be different with other user even using same browser
=> fix(admin-ui): update theme lang config and condition

admin-ui/plugins/schema/redux/api/AttributeApi.js, admin-ui/plugins/schema/redux/reducers/AttributeReducer.js, admin-ui/plugins/schema/redux/sagas/AttributeSaga.js, admin-ui/plugins/user-management/components/UserManagement/UserList.js
https://github.com/GluuFederation/flex/issues/420
=> fix(admin-ui): fix attribute api change for users plugin

admin-ui/app/routes/Dashboards/Chart/DashboardChart.js
Fix the Dashboard chart overlap
=> feat(admin-ui): fix dashboard chart

flex-linux-setup/flex_linux_setup/flex_setup.py
https://github.com/GluuFederation/flex/issues/426
=> feat: generate jans-config-api client from multiple swagger specs #426

admin-ui/plugins/auth-server/components/Clients/ClientDetailPage.js
fixed bug on client details page.
=> Fixed bug on client details page. 440

admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js
Enabled search component for script page.
=> Enabled search component for script page. 436

admin-ui/app/redux/api/MauApi.js, admin-ui/configApiSpecs.yaml, admin-ui/plugins/schema/redux/api/AttributeApi.js, admin-ui/plugins/schema/redux/reducers/AttributeReducer.js, admin-ui/plugins/user-management/redux/reducers/UserReducer.js
https://github.com/GluuFederation/flex/issues/448
=> fix(admin-ui): Fix Dashboard, User Management and Person page.

admin-ui/plugins/admin/redux/api/MappingApi.js, admin-ui/plugins/admin/redux/api/PermissionApi.js, admin-ui/plugins/admin/redux/api/RoleApi.js
https://github.com/GluuFederation/flex/issues/444
=> feat: code refactoring following api change #444

admin-ui/plugins/auth-server/components/Scopes/ScopeListPage.js, admin-ui/plugins/auth-server/redux/api/ScopeApi.js, admin-ui/plugins/auth-server/redux/reducers/ScopeReducer.js, admin-ui/plugins/auth-server/redux/sagas/OAuthScopeSaga.js, admin-ui/plugins/schema/redux/api/AttributeApi.js, admin-ui/plugins/user-management/redux/api/UserApi.js
https://github.com/GluuFederation/flex/issues/449
=> feat(admin-ui): implement server side pagination for scope page

admin-ui/app/redux/api/LicenseApi.js
https://github.com/GluuFederation/flex/issues/454
=> fix:  license feature not working #454

admin-ui/plugins/auth-server/components/Clients/ClientListPage.js, admin-ui/plugins/auth-server/redux/api/OIDCApi.js, admin-ui/plugins/auth-server/redux/reducers/OIDCReducer.js, admin-ui/plugins/auth-server/redux/sagas/OIDCSaga.js
https://github.com/GluuFederation/flex/issues/447
=> feat(admin-ui): implement server side pagination for OICD client page

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat: flex-linux-setup uninstall

admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js
https://github.com/GluuFederation/flex/issues/468
=> fix(admin-ui): implement refresh on change of type for scripts page

admin-ui/plugins/user-management/components/UserManagement/UserList.js, admin-ui/plugins/user-management/redux/reducers/UserReducer.js
https://github.com/GluuFederation/flex/issues/469
=> feat(admin-ui): implement server side pagination on user management screen

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat: flex-linux-setup option -download-exit

casa/app/src/main/resources/labels/admin.properties, casa/app/src/main/webapp/header.zul, casa/pom.xml
=> chore(casa): update jackson-databind lib for vulnerability

admin-ui/package.json
https://github.com/GluuFederation/flex/issues/487
=> fix: admin-ui not working #487

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: jans-linux-setup set Jannsen version to 1.0.3

admin-ui/app/utils/Util.js, admin-ui/plugins/auth-server/components/Clients/ClientBasicPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientSoftwarePanel.js
fix [object Object] on client basic and software panel.
=> fix [object Object] on client basic and software panel. issue 437

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup download node

admin-ui/app/redux/api/InitApi.js, admin-ui/app/redux/reducers/InitReducer.js
https://github.com/GluuFederation/flex/issues/499
=> fix(admin-ui): fix api change for custom scripts to be shown in scopes page

admin-ui/plugins/auth-server/components/Clients/ClientListPage.js
https://github.com/GluuFederation/flex/issues/502
=> fix(admin-ui): Change get scopes limit to 100 on clients page

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup nod download

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup-replace replace-shlex.join() by subprocess.list2cmdline()

admin-ui/app/components/agGrid.js, admin-ui/app/styles/plugins/_ag-grid.scss, admin-ui/app/styles/plugins/_react-image-crop.scss, admin-ui/app/styles/plugins/plugins.scss, admin-ui/package.json
=> fix(admin-ui): sass issue after upgrade some dependencies

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.properties
=> Flex linux setup admin UI client

admin-ui/app/routes/Apps/Gluu/GluuSessionTimeout.js
update IdleTimer component due to react-idle-timer upgrade
https://idletimer.dev/docs/getting-started/new#removal-of-idletimer--component 
https://github.com/GluuFederation/flex/pull/534
=> feat(admin-ui): update IdleTimer component due to react-idle-timer upgrade

casa/extras/enrollment-client/enroll.js
=> fix: scope names correction

admin-ui/app/utils/PermChecker.js, admin-ui/plugins/admin/components/Mapping/MappingItem.js, admin-ui/plugins/admin/components/Mapping/MappingPage.js, admin-ui/plugins/admin/components/Permissions/UiPermListPage.js, admin-ui/plugins/admin/components/Roles/UiRoleListPage.js, admin-ui/plugins/admin/plugin-metadata.js
Implement Validation on following pages
1. Dashboard
2. Config API > Access Role
3. Config API > Permissions
4. Config API > Mapping
5. Scripts
=> feat(admin-ui): view edit delete validation for pages.

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/templates/auiConfiguration.properties.tmpl
=> feat(image): use admin-ui client encoded secret to render properties

admin-ui/app/utils/PermChecker.js
https://github.com/GluuFederation/flex/issues/576
=> fix: use correct jans_stat permission #576

admin-ui/plugins/user-management/components/UserManagement/UserForm.js
https://github.com/GluuFederation/flex/issues/581
=> fix(admin-ui): Claims are not populating in User Management 

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup version 1.0.4-SNAPSHOT

admin-ui/build/cli-tools.js, admin-ui/build/plugin-cli.js, flex-linux-setup/README.md
https://github.com/GluuFederation/flex/issues/589
=> fix: fix plugin installation script #589

admin-ui/app/styles/main.scss, admin-ui/plugins/auth-server/components/Clients/ClientDetailPage.js, admin-ui/plugins/auth-server/components/Clients/ClientListPage.js
Update and adjust some styling issue due to reactstrap upgrade
=> feat(admin-ui): reactstrap styling update

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt
The changeset updates upstream dependencies which fix plugins loading.
=> chore(image): update dependencies to fix admin-ui plugins

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup prompts

casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/SmppMobilePhoneService.java, casa/pom.xml
=> chore: fix compilation

casa/pom.xml
=> chore: update jackson version 

docker-casa/Dockerfile, docker-casa/requirements.txt
=> chore(image): update casa image dependencies

admin-ui/plugins/auth-server/components/Clients/ClientScriptPanel.js, admin-ui/plugins/user-management/components/UserManagement/UserEditPage.js
https://github.com/GluuFederation/flex/issues/624
=> fix(admin-ui): User and Client page crash fix

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-admin-ui/templates/clients.ldif, docker-casa/Dockerfile, docker-casa/requirements.txt
=> chore(image): sync static files and templates from upstream

admin-ui/plugins/schema/components/Person/AttributeForm.js
https://github.com/GluuFederation/flex/issues/617
=> fix(admin-ui): Fix schema > attributes edit values not auto selected for dropdown

admin-ui/plugins/auth-server/components/Configuration/ConfigPage.js
https://github.com/GluuFederation/flex/issues/635
=> fix: auth server configuration are not saving in admin-ui #635

admin-ui/plugins/auth-server/components/Clients/ClientListPage.js, admin-ui/plugins/auth-server/components/Configuration/ConfigPage.js
https://github.com/GluuFederation/flex/issues/638
=> fix(admin-ui): fix 2 bugs #638

casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/Fido2Service.java, casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/SGService.java
=> fix: fix compilation errors 

admin-ui/app/components/App/AuthenticatedRouteSelector.js, admin-ui/app/locales/en/translation.json, admin-ui/app/redux/actions/ToastAction.js, admin-ui/app/redux/actions/types.js, admin-ui/app/redux/reducers/ToastReducer.js, admin-ui/app/redux/reducers/index.js, admin-ui/app/routes/Apps/Gluu/GluuToast.js, admin-ui/plugins/admin/redux/sagas/ApiPermissionSaga.js, admin-ui/plugins/admin/redux/sagas/ApiRoleSaga.js, admin-ui/plugins/admin/redux/sagas/CustomScriptSaga.js, admin-ui/plugins/admin/redux/sagas/MappingSaga.js, admin-ui/plugins/auth-server/redux/sagas/JsonConfigSaga.js, admin-ui/plugins/auth-server/redux/sagas/LoggingSaga.js, admin-ui/plugins/auth-server/redux/sagas/OAuthScopeSaga.js, admin-ui/plugins/auth-server/redux/sagas/OIDCSaga.js, admin-ui/plugins/schema/redux/sagas/AttributeSaga.js, admin-ui/plugins/services/redux/sagas/CacheSaga.js, admin-ui/plugins/user-management/redux/sagas/UserSaga.js
https://github.com/GluuFederation/flex/issues/543
=> feat(admin-ui): add informative action message for all change data endpoint

admin-ui/app/redux/api/axios.js, admin-ui/app/redux/api/backend-api.js, admin-ui/app/redux/api/index.js
https://github.com/GluuFederation/flex/issues/649
=> feat: apis changes in admin-ui #649

flex-linux-setup/flex_linux_setup/flex_setup.py
Implement flex-linux-setup part of issue https://github.com/GluuFederation/flex/issues/664
=> feat: flex-linux-setup use tarball to install node_modules in admin-ui

admin-ui/app/routes/Apps/Gluu/GluuInputRow.js, admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js, admin-ui/plugins/auth-server/components/Clients/ClientBasicPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientEditPage.js, admin-ui/plugins/auth-server/components/Clients/ClientListPage.js, admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js, admin-ui/plugins/auth-server/components/Scopes/ScopeListPage.js, admin-ui/plugins/auth-server/redux/sagas/OIDCSaga.js, admin-ui/plugins/schema/components/Person/AttributeListPage.js, admin-ui/plugins/services/redux/api/LdapApi.js, admin-ui/plugins/services/redux/sagas/LdapSaga.js, admin-ui/plugins/user-management/components/UserManagement/UserAddPage.js, admin-ui/plugins/user-management/components/UserManagement/UserEditPage.js, admin-ui/plugins/user-management/components/UserManagement/UserForm.js, admin-ui/plugins/user-management/components/UserManagement/UserList.js
https://github.com/GluuFederation/flex/issues/663
=> fix(admin-ui): fix multiple issues

admin-ui/plugins/user-management/components/UserManagement/UserList.js
https://github.com/GluuFederation/flex/issues/675
=> fix(admin-ui): implement limit on users page

casa/pom.xml
=> fix(casa): weld startup errors

docker-casa/Dockerfile, docker-casa/conf/jans-mysql.properties.tmpl, docker-casa/conf/jans-pgsql.properties.tmpl, docker-casa/jetty/casa.xml, docker-casa/requirements.txt, docker-casa/scripts/bootstrap.py, docker-casa/scripts/entrypoint.sh, docker-casa/scripts/mod_context.py
Overview:
- Fixed errors when using Postgres persistence (closes #680)
- Fixed errors when using Spanner and Couchbase persistence (closes #683)
=> fix(docker-casa): handle startup errors on postgres, spanner, and couchbase persistence

admin-ui/app/locales/en/translation.json, admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
https://github.com/GluuFederation/flex/issues/687
=> feat(admin-ui): implement finish button on client

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup Dump Admin UI Client and Secret to screen and setup.properties

casa/extras/README.md
=> docs: first draft

flex-linux-setup/flex_linux_setup/flex_setup.py
=> flex: flex-linux-setup enable basic auth script

casa/app/pom.xml, casa/pom.xml
=> chore: update pf4j and nimbus libraries to latest 

admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
https://github.com/GluuFederation/flex/issues/695
=> feat(admin-ui): change redirect url mandatory logic

admin-ui/app/routes/Apps/Gluu/GluuCommitDialog.js, admin-ui/app/routes/Apps/Gluu/GluuInlineInput.js
https://github.com/GluuFederation/flex/issues/711
=> fix(admin-ui): fix type ahead new entry issue and fix modal to show items correctly

admin-ui/app/routes/Apps/Gluu/GluuInlineInput.js
https://github.com/GluuFederation/flex/issues/715
=> fix(admin-ui): boolean and string shows undefined fixed

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> Flex linux setup adminui auth mode

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-casa/Dockerfile, docker-casa/requirements.txt
The changeset updates schema,templates, and config from upstream (Flex and Janssen).
Closes #730
=> chore(docker): sync schema, templates, and config from upstream

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup check twilio and fido2 client before deploy

demos/terraform-gluu-flex-eks-fargate/README.md
Features
* initial structure )
* initial structure )
* remove update lb ip script )
* variable name and formate )
=> fix(terraform-gluu-flex-eks-fargate): update terraform module

admin-ui/openapi-merge.json
https://github.com/GluuFederation/flex/issues/732
closes#732
=> fix: error on getting API response from jans-config-api server #732

docker-admin-ui/Dockerfile, docker-admin-ui/templates/auiConfiguration.json, docker-casa/Dockerfile, docker-flex-monolith/Dockerfile
=> chore(docker): sync manifests from upstream

casa/app/src/main/java/org/gluu/casa/timer/AuthnScriptsReloader.java
=> bug(casa): automatic script reload not working

casa/config/pom.xml, casa/plugins/cert-authn/pom.xml, casa/plugins/custom-branding/pom.xml, casa/plugins/strong-authn-settings/pom.xml, casa/pom.xml
=> bug(casa): fix compilation issues

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: flex-linux-setup remove Casa.py

docs/install/vm-install/ubuntu.md
Corrected the github repo package location
=> docs: updated package location address

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> fix(flex-linux-setup)  download exit

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
- feat: create credentials encryption private and public key
=> feat: Admin UI License Registration

casa/app/src/main/java/org/gluu/casa/core/model/Fido2RegistrationEntry.java, casa/app/src/main/java/org/gluu/casa/core/pojo/SuperGluuDevice.java, casa/app/src/main/java/org/gluu/casa/misc/CustomClassLoader.java, casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/SecurityKey2Extension.java, casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/rs/SuperGluuEnrollingWS.java, casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/Fido2Service.java, casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/FidoService.java, casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/SGService.java, casa/app/src/main/java/org/gluu/casa/ui/vm/user/SecurityKey2ViewModel.java, casa/app/src/main/java/org/gluu/casa/ui/vm/user/SuperGluuViewModel.java, casa/extras/Casa.py, casa/extras/casa-external_fido2.py, casa/extras/casa-external_super_gluu.py, casa/shared/src/main/java/org/gluu/casa/misc/WebUtils.java
=> fix(casa): errors in casa script

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-casa/Dockerfile, docker-casa/requirements.txt, docker-flex-monolith/Dockerfile
Updates overview:
- `jans-pycloudlib`
- janssen source
- flex source
Closes #793
=> chore(docker): update image dependencies

docs/install/README.md, docs/install/vm-install/README.md, docs/install/vm-install/ubuntu.md, mkdocs.yml
This PR contains some changes to landing pages in Installation and adding Ubuntu 22 to those installation instructions.
=> docs: installation landing page, ubuntu 22 updates

admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js, admin-ui/plugins/admin/plugin-metadata.js, admin-ui/plugins/auth-server/components/Clients/ClientListPage.js, admin-ui/plugins/auth-server/components/Scopes/ScopeListPage.js, admin-ui/plugins/auth-server/plugin-metadata.js, admin-ui/plugins/schema/components/Person/AttributeListPage.js, admin-ui/plugins/schema/plugin-metadata.js, admin-ui/plugins/services/Components/Configuration/LdapListPage.js, admin-ui/plugins/services/Components/Configuration/SqlListPage.js, admin-ui/plugins/services/plugin-metadata.js, admin-ui/plugins/user-management/components/UserManagement/UserList.js, admin-ui/plugins/user-management/plugin-metadata.js
https://github.com/GluuFederation/flex/issues/808
=> fix(admin-ui): fix edit and view pages issue

admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
https://github.com/GluuFederation/flex/issues/807
=> fix: redirect_uris is mandatory if grant_types is not selected #807

docs/reference/kubernetes/helm-chart.md
=> fix(docs): autogenerate docs

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> feat(flex-linux-setup): Admin UI License Registration

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): decoding ssa jwt

admin-ui/app/utils/ApiKeyRedirect.js, admin-ui/app/utils/ViewRedirect.js
https://github.com/GluuFederation/flex/issues/497
=> feat: change error message#497

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> fix(flex-linux-setup) grab oidc client registration url from ssa

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): set flex version 1.0.9

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): no download for deb/rpm packages

admin-ui/app/routes/Apps/Gluu/GluuLabel.js, admin-ui/plugins/user-management/components/UserManagement/UserForm.js
https://github.com/GluuFederation/private/issues/1846
=> fix(admin-ui): Tab skip tooltip and make middle name not required field

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): enforce SSA

docker-admin-ui/Dockerfile, docker-admin-ui/README.md, docker-admin-ui/requirements.txt, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/scripts/ssa.py, docker-admin-ui/scripts/wait.py, docker-admin-ui/templates/auiConfiguration.json
The changeset adds feature to get license credentials from SCAN.
Closes #814
=> feat(docker-admin-ui): admin-ui license registration

admin-ui/app/routes/Apps/Gluu/GluuErrorModal.js, admin-ui/app/utils/ApiKeyRedirect.js, admin-ui/app/utils/ViewRedirect.js
https://github.com/GluuFederation/flex/issues/843
=> feat(admin-ui): Change design for backend error

docs/install/vm-install/ubuntu.md
Adjusted package names in Ubuntu to align with new naming convention.
=> docs: aligned links with new package names

admin-ui/app/components/OuterClick/OuterClick.js, admin-ui/plugins/auth-server/components/Configuration/JsonPropertyBuilder.js
https://github.com/GluuFederation/flex/issues/848
=> fix(admin-ui): fix properties page blank issues

admin-ui/plugins/auth-server/components/Configuration/DefaultAcrInput.js
https://github.com/GluuFederation/flex/issues/851
=> fix(admin-ui): fix default authentication method. 

admin-ui/plugins/auth-server/components/Scopes/ScopeListPage.js
=> fix: newly added scope is not showing #812

admin-ui/app/components/UncontrolledTabs/UncontrolledTabsNavLink.js, admin-ui/app/routes/Apps/Profile/ProfilePage.js, admin-ui/app/routes/components/HeaderMain.js, admin-ui/app/routes/components/Profile.js
=> fix: labels are not appearing in admin ui profile in dark mode #855

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): don't assk ssa when provided in args

admin-ui/plugins/auth-server/components/Configuration/ConfigPage.js
https://github.com/GluuFederation/flex/issues/726
=> feat(admin-ui): Implement search on properties page

docs/install/vm-install/suse.md
There was a typo in the installation command package link.
=> docs: updated SUSE install link

docker-admin-ui/Dockerfile, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/scripts/ssa.py, docker-admin-ui/templates/auiConfiguration.json
The changeset introduces changes to admin-ui configuration as mentioned in #884.
=> feat(docker-admin-ui): changes in admin-ui configuration

admin-ui/plugins/auth-server/components/Clients/ClientBasicPanel.js
=> fix: implement pagination api to fetch scopes

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Gluu/GluuScriptErrorModal.js, admin-ui/plugins/admin/components/CustomScripts/CustomScriptAddPage.js, admin-ui/plugins/admin/components/CustomScripts/CustomScriptForm.js, admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js, admin-ui/plugins/admin/redux/sagas/CustomScriptSaga.js, admin-ui/plugins/auth-server/components/Clients/ClientShowScopes.js
issue #882 
PR includes changes,
1. added Show Error button to open a modal displaying script error
2. added validation for **Name** field
3. navigate user to list view if script is saved successfully
=> feat: feature to show error on custom scripts

admin-ui/app/locales/en/translation.json, admin-ui/plugins/services/Components/Configuration/LdapForm.js, admin-ui/plugins/services/redux/api/LdapApi.js
https://github.com/GluuFederation/private/issues/1973
=> feat(admin-ui): add test connection functionality and change some titles on create LDAP screen

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/casa_scopes.json
=> feat(flex-linux-setup): casa client scopes

casa/app-fips/pom.xml, casa/pom.xml
**bc-fips** support has been added for usage on RHEL (DISA-STIG) platform .
Issue: https://github.com/GluuFederation/flex/issues/941
=> fix: casa: bc-fips build has been added;

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat(flex-linux-setup): add org_id to client display name

admin-ui/plugins/services/Components/Configuration/LdapAddPage.js, admin-ui/plugins/services/Components/Configuration/LdapEditPage.js, admin-ui/plugins/services/Components/Configuration/LdapForm.js
=> fix: ldap update not working #957

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat(flex-linux-setup): node version 18.16.0

admin-ui/app/components/Notifications/styles.js, admin-ui/plugins/auth-server/components/AuthN/AuthNListPage.js, admin-ui/plugins/auth-server/components/AuthN/styles.js
issue: #745 
removed remaining `@material-ui` imports in the project.
=> fix: removed material-ui imports in project

docker-admin-ui/Dockerfile, docker-admin-ui/Makefile, docker-admin-ui/requirements.txt, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/scripts/ssa.py, docker-admin-ui/templates/auiConfiguration.json
Overview:
- upgrade NodeJS and NPM version
- changes to `licenseConfig`
- fix Makefile rule
=> chore(docker-admin-ui): sync assets and env for admin-ui image

docker-casa/Dockerfile, docker-casa/README.md, docker-casa/scripts/bootstrap.py, docker-casa/scripts/entrypoint.sh, docker-casa/scripts/upgrade.py
Overview:
- adds new scopes for casa (closes #968)
- add env var to configure default http size limit when retrieving remote JWKS (closes #969)
=> chore(docker-casa): add casa scopes and nimbusds remote jwks size limit

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): set redirect_uris to iss

admin-ui/app/routes/Apps/Gluu/GluuTypeAheadWithAdd.js
issue #978 
fixes: Expanded button UI
=> fix(admin-ui): changed input & button layout

flex-linux-setup/flex_linux_setup/flex_setup.py
In this PR:
`--update-admin-ui` arument was added to `flex_setup.py` so that Gluu Flex Admin UI can be upgraded
closes #990
=> feat(flex-linux-setup): upgrade admin-ui

casa/plugins/email_2fa_core/README.md, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/model/EmailPerson.java, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/model/SmtpConfiguration.java, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/model/VerifiedEmail.java
- function **equals(...)** has been overrided in some classes;
- small fixes of formatting;
=> feat: email_2fa_core: improvements of code have been added;

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Gluu/GluuSelectRow.js, admin-ui/plugins/smtp-management/components/SmtpManagement/SmtpForm.js
=> chore: changes in SMTP form #1026

casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/Fido2Service.java, casa/app/src/main/java/org/gluu/casa/ui/vm/user/SecurityKey2ViewModel.java, casa/plugins/email_2fa_core/extras/README.md, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/credentials/extensions/EmailOtpAuthnMethod.java, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/EmailOtpInitiator.java, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/EmailOtpPlugin.java, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/EmailOtpService.java, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/EmailOtpVM.java, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/model/EmailPerson.java, casa/plugins/email_2fa_core/src/main/java/org/gluu/casa/plugins/emailotp/model/JansConfiguration.java
1. **email_2fa_core**: has been re-factored;
1. **email_2fa_core**: **README.md** has been updated;
1. **email_2fa_core**: **EmailOtpService.getConfiguration()** has been updated, according to SQL deployment;
1. **fido2**: removing of device has been updated;
=> feat: email_2fa_core: improvements of code have been added (2);

flex-linux-setup/flex_linux_setup/flex_setup.py
closes #1030
- Provide SSA either file or jwt via arg: 
`--admin-ui-ssa=/root/ssa.txt` or `-admin-ui-ssa="eyJraWQiOiJzc2FfYzY5Z ..... D1hKBvLQ"`
- When prompted you can either write path of file containing SSA or pas SSA JWT:
```
Please wait while collecting properties...
Install Admin UI [Y/n]: y
Please enter path of file containing SSA or paste SSA (q to exit): eyJraWQiOiJzc2FfYzY5ZjQ0MjUtYWYwMS00OTA0LThiNmMtOGMyYjQwN2YxNzhmX3NpZ19yczI1NiIsInR5cCI6Imp3dCIsImFsZyI6IlJTMjU2In .....
```
or 
```
Please wait while collecting properties...
Install Admin UI [Y/n]: y
Please enter path of file containing SSA or paste SSA (q to exit):  /root/ssa.txt
```
- provide SSA file or JWT directily in setup.properties:
```
install-admin-ui=True
gluu-passwurd-cert=False
install-casa=False …
```
=> feat(flex-linux-setup): paste SSA when prompted

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): typo

flex-linux-setup/flex_linux_setup/flex_setup.py
closes https://github.com/GluuFederation/flex/issues/1052
=> fix(flex-linux-setup): set licenseHardwareKey to org_id from ssa

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/package.json, admin-ui/plugins/auth-server/components/Agama/AgamaListPage.js
=> feat(admin-ui): check or warn if Agama engine is enabled before project uploading #1036

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/plugins/auth-server/components/Agama/AgamaListPage.js, admin-ui/plugins/auth-server/components/Agama/AgamaProjectConfigModal.js
=> chore(admin-ui): misc adjustments in Agama screens #1035

admin-ui/plugins/auth-server/components/Clients/ClientAdvancedPanel.js
=> fix: Storing ACR value is inserting inum instead of displayName #1079

admin-ui/plugins/schema/components/Person/AttributeViewPage.js
=> fix(admin-ui): app crashes on visiting attribute view screen #1099

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix: rename admin-ui plugin

admin-ui/app/redux/sagas/LicenseSaga.js
=> fix(admin-ui): show error message if generated trial key fails #1110

admin-ui/plugins/auth-server/components/Clients/ClientAddPage.js, admin-ui/plugins/auth-server/components/Clients/ClientBasicPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientEditPage.js, admin-ui/plugins/auth-server/redux/features/scopeSlice.js
=> fix(admin-ui): unable to add openid scope while creating AS client #1115

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): remove duo script

admin-ui/plugins/auth-server/components/Agama/AgamaListPage.js, admin-ui/plugins/auth-server/redux/features/agamaSlice.js, admin-ui/plugins/auth-server/redux/sagas/AgamaSaga.js
=> fix(admin-ui): agama deployment page is inaccessible #1136

docs/install/vm-install/suse.md, docs/install/vm-install/vm-requirements.md
updated firewall and other instructions
closes:#1133
=> updated firewall and other instructions

docs/install/vm-install/ubuntu.md
Update ubuntu.md for flex changes
closes: #1133
=> Update ubuntu.md for flex changes

docs/install/vm-install/rhel.md
=> Update vm doc rhel.md

casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/rs/OTPEnrollingWS.java, casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/otp/HOTPAlgorithmService.java, casa/app/src/main/java/org/gluu/casa/plugins/authnmethod/service/otp/TOTPAlgorithmService.java, casa/app/src/main/java/org/gluu/casa/ui/vm/user/OTPViewModel.java, casa/extras/casa-external_otp.py
=> fix: use url base64 encoding in casa for enrollment

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat(flex-linux-setup): passwurd api keystore tweaks

docs/install/vm-install/rhel.md
Update and fix instructions for RHEL VM installation
=> docs: fix RHEL VM instructions

admin-ui/app/utils/AppAuthProvider.js
=> fix(admin-ui): sequential license api calls #1151

flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
closes #1154
(3) is implemented in this PR
(1) and (2) is implemented in https://github.com/JanssenProject/jans/pull/5362
=> fix(flec-linux-setup): opHost changes

admin-ui/plugins/schema/presentation/pages/AttributeListPage.tsx, admin-ui/plugins/user-management/components/UserManagement/UserList.js
issue #1158 
**changes**
- fixed blank screen issue
- added `useCallback`dependency in `TablePagination` Attribute list screen
=> fix(admin-ui): page goes blank on random users search #1158

docker-admin-ui/Dockerfile, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/templates/auiConfiguration.json
The changeset modifies `opHost` value found in admin-ui configuration.
Closes #1161
=> chore(docker-admin-ui): change opHost value

admin-ui/app/redux/api/base.js, admin-ui/app/redux/features/initSlice.js, admin-ui/app/redux/features/licenseSlice.js, admin-ui/app/redux/sagas/LicenseSaga.js, admin-ui/app/redux/sagas/SagaUtils.js, admin-ui/app/redux/store/index.ts, admin-ui/app/routes/Apps/Gluu/GluuTimeoutModal.js, admin-ui/app/utils/ApiKeyRedirect.js, admin-ui/app/utils/ApiUtils.js, admin-ui/app/utils/AppAuthProvider.js, admin-ui/build/webpack.config.client.dev.js, admin-ui/build/webpack.config.client.prod.js, admin-ui/plugins/fido/domain/use-cases/dynamicConfigUseCases.ts, admin-ui/plugins/fido/domain/use-cases/fidoUseCases.ts, admin-ui/plugins/fido/domain/use-cases/staticConfigUseCases.ts
=> fix(admin-ui): show an error screen on license api timeout #1163

docker-admin-ui/Makefile, docker-casa/Dockerfile, docker-casa/Makefile
Overview:
- fix docker-casa version label
- ensure Makefile rule reads required value from Dockerfile
Closes #1169
=> ci(docker): incorrect image build version

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/redux/features/initSlice.js, admin-ui/app/routes/Apps/Gluu/GluuErrorModal.js, admin-ui/app/routes/Apps/Gluu/GluuTimeoutModal.js, admin-ui/app/utils/AppAuthProvider.js
=> fix(admin-ui): api timeout popup modification #1175

admin-ui/app/components/Notifications/index.js, admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Gluu/GluuAppSidebar.js, admin-ui/app/routes/Apps/Gluu/GluuTypeAhead.js, admin-ui/app/routes/Dashboards/Chart/DashboardChart.js, admin-ui/app/routes/Dashboards/DashboardPage.js, admin-ui/app/utils/ApiResources.js, admin-ui/plugins/admin/components/Mapping/MappingItem.js, admin-ui/plugins/admin/components/Permissions/UiPermDetailPage.js, admin-ui/plugins/admin/components/Permissions/UiPermListPage.js, admin-ui/plugins/admin/components/Roles/UiRoleDetailPage.js, admin-ui/plugins/admin/redux/features/apiPermissionSlice.js, admin-ui/plugins/admin/redux/features/mappingSlice.js, admin-ui/plugins/admin/redux/sagas/ApiPermissionSaga.js, admin-ui/plugins/auth-server/components/AuthN/AuthNDetailPage.js, admin-ui/plugins/auth-server/components/Ssa/SsaDetailPage.js, admin-ui/plugins/cache-refresh/components/CacheRefresh/CacheRefreshManagement.js, admin-ui/plugins/cache-refresh/components/Tabs/SourceBackendServersTab.js, admin-ui/plugins/cache-refresh/plugin-metadata.js, admin-ui/plugins/schema/presentation/pages/AttributeListPage.tsx
=> fix(admin-ui): issues in admin-ui #1165

admin-ui/plugins/auth-server/redux/api/AgamaApi.js
=> fix(admin-ui): remove agama developer studio #1182

admin-ui/app/redux/api/LicenseApi.js, admin-ui/app/redux/api/LicenseDetailsApi.js, admin-ui/app/utils/ApiUtils.js
=> feat: retry license requests if there is timeout #1176

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat(flex-linux-setup): option --no-restart-services

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): strip inputs

admin-ui/app/redux/features/authSlice.js, admin-ui/app/redux/sagas/AuthSaga.js, admin-ui/app/redux/sagas/LicenseSaga.js, admin-ui/app/redux/store/index.ts, admin-ui/app/routes/Dashboards/DashboardPage.js, admin-ui/app/utils/AppAuthProvider.js, admin-ui/plugins/user-management/components/UserManagement/UserList.js
=> fix(admin-ui): remove unnecessary HTTP requests from UI #1190

admin-ui/plugins/jans-link/components/CacheRefresh/JansLinkPage.test.js, admin-ui/plugins/jans-link/components/Tabs/CacheRefreshTab.js, admin-ui/plugins/jans-link/components/Tabs/InumDBServerTab.js
=> fix(admin-ui): jans-link save in admin-ui not working due changes in api #1194

admin-ui/plugins/smtp-management/redux/sagas/SmtpSaga.js
=> fix(admin-ui): smtp configuration test is failing #1209

admin-ui/plugins/jans-link/components/Tabs/InumDBServerTab.js, admin-ui/plugins/jans-link/components/Tabs/SourceBackendServersTab.js
=> fix(admin-ui): change bind password not working #1214

admin-ui/plugins/jans-link/components/Tabs/CacheRefreshTab.js
=> fix(admin-ui): jans-link not opening in admin-ui after running job #1217

docs/install/vm-install/suse.md
=> Update suse.md for enable package

admin-ui/plugins/admin/components/CustomScripts/CustomScriptEditPage.js, admin-ui/plugins/admin/components/CustomScripts/CustomScriptForm.js
=> fix(admin-ui): custom script with location type file is not saving #1226

admin-ui/app/redux/api/backend-api.js, admin-ui/app/redux/features/authSlice.js, admin-ui/app/redux/sagas/AuthSaga.js, admin-ui/app/utils/AppAuthProvider.js, admin-ui/app/utils/RandomHashGenerator.js
=> feat: adding PKCE in admin-ui authentication #1221

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat(flex-linux-setup): update admin-ui config-api plugin

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): admin-ui plugin path after upgrade

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): don't backup jar file in upgrade

flex-linux-setup/README.md
=> docs: update vm resources requirements

admin-ui/app/routes/Apps/Gluu/GluuTypeAheadWithAdd.js, admin-ui/plugins/admin/components/Roles/UiRoleListPage.js, admin-ui/plugins/auth-server/components/Clients/ClientBasicPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientCibaParUmaPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js, admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js, admin-ui/plugins/jans-link/components/CacheRefresh/JansLinkPage.js, admin-ui/plugins/jans-link/components/Tabs/ConfigurationTab.js, admin-ui/plugins/user-management/components/UserManagement/UserEditPage.js
=> fix(admin-ui): bugs in admin-ui #1225

admin-ui/plugins/jans-link/components/Tabs/SourceBackendServersTab.js
=> fix(admin-ui): jans-link source backend ldap servers field label changes #1253

admin-ui/plugins/jans-link/components/Tabs/InumDBServerTab.js, admin-ui/plugins/jans-link/components/Tabs/SourceBackendServersTab.js
=> fix(admin-ui): not able to save base dn in source backend ldap & inum db #1258

admin-ui/plugins/services/plugin-metadata.js
=> feat(admin-ui): remove mysql and couchbase schema configuration menus from admin ui #1263

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/plugins/jans-link/components/Tabs/ConfigurationTab.js, admin-ui/plugins/jans-link/components/Tabs/SourceBackendServersTab.js
=> feat(admin-ui): remove Server IP Address field & ldap test action #1266

admin-ui/app/routes/Apps/Gluu/GluuProperties.js, admin-ui/app/routes/Apps/Gluu/GluuPropertyItem.js, admin-ui/plugins/admin/redux/features/customScriptSlice.js, admin-ui/plugins/jans-link/components/Tabs/ConfigurationTab.js
=> fix(admin-ui): source & destination react component malfunctioning #1269

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Gluu/GluuCommitDialog.js, admin-ui/app/routes/Apps/Gluu/GluuTabs.js, admin-ui/plugins/jans-link/components/CacheRefresh/JansLinkPage.js, admin-ui/plugins/jans-link/components/SourceBackendServers/SourceBackendServerForm.js, admin-ui/plugins/jans-link/components/Tabs/SourceBackendServersTab.js, admin-ui/plugins/jans-link/plugin-metadata.js, admin-ui/plugins/jans-link/redux/features/CacheRefreshSlice.js, admin-ui/plugins/jans-link/redux/sagas/CacheRefreshSaga.js
=> feat(admin-ui): jans-link UI changes #1287

admin-ui/build/webpack.config.client.prod.js
=> feat(admin-ui): add favicon in admin ui #1290

admin-ui/openapi-merge.json
=> fix(admin-ui): change admin ui license api spec branch in json file #1295

casa/app/pom.xml, casa/pom.xml
=> chore(casa): upgrade nimbusds oauth2-oidc-sdk library

admin-ui/app/components/Notifications/index.js, admin-ui/package.json
=> fix(admin-ui): resolve sass warnings on local dev server #1301

admin-ui/app/redux/sagas/LicenseSaga.js
=> fix(admin-ui): display upload ssa UI if configs are not valid #1310

.github/workflows/build-docs.yml, mkdocs.yml
As described in #1318 
closes #1318
=> fix(docs): fix syntax error in nav structure

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> feat(flex-linux-setup): add adminu ui token client

docs/admin/admin-ui/faq.md, docs/install/vm-install/rhel.md, docs/install/vm-install/suse.md, docs/install/vm-install/ubuntu.md
=> docs: adding command to uninstall and update admin-ui #1326

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/plugins/auth-server/redux/features/scopeSlice.js, admin-ui/plugins/fido/components/Fido.js, admin-ui/plugins/fido/plugin-metadata.js
=> feat(admin-ui): implement navigation path for tab view in a page #1333

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Gluu/GluuSelectRow.js, admin-ui/plugins/fido/components/DynamicConfiguration.js, admin-ui/plugins/jans-link/components/Tabs/ConfigurationTab.js
=> feat(admin-ui): logging level in jans-link #1351

admin-ui/app/components/Layout/Layout.js, admin-ui/app/components/SidebarTrigger/SidebarTrigger.js, admin-ui/app/routes/Apps/Gluu/GluuNavBar.js, admin-ui/app/styles/miltonbo/scss/_navbar.scss
=> fix(admin-ui): display of sidebar menu on small screen sizes #1338

admin-ui/app/redux/sagas/LicenseSaga.js
=> fix(admin-ui): allow user to login page on emtpy stat results #1356

admin-ui/app/components/Wizard/WizardStep.js, admin-ui/plugins/auth-server/__tests__/components/ClientWizardForm.test.js, admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
=> feat(admin-ui): add test cases in client wizard form #1358

docs/install/vm-install/suse.md
=> docs: update suse.md

admin-ui/app/redux/sagas/LicenseSaga.js
=> fix(admin-ui): isActive endpoint called twice on ssa upload #1369

docs/admin/README.md, docs/admin/recipes/getting-started-rancher.md
=> refactor(docs): align casa references to Jans Casa

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> feat(flex-linux-setup): change client name

flex-linux-setup/flex_linux_setup/flex_setup.py
=> Version 1.0.20-SNAPSHOT

docs/install/vm-install/rhel.md, docs/install/vm-install/suse.md, docs/install/vm-install/ubuntu.md
=> Update certbot instruction

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/scripts/builder.py, docker-admin-ui/scripts/ssa.py, docker-admin-ui/templates/admin-ui/auiConfiguration.json, docker-admin-ui/templates/admin-ui/clients.ldif
Add support for lock.
Closes #1404
=> chore(docker-admin-ui): add lock support for admin-ui image

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat(flex-linux-setup): change admin-ui log location to /var/log/adminui

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Dashboards/DashboardPage.js
=> fix: inaccuracy in displaying license details #1411

admin-ui/app/redux/api/backend-api.js, admin-ui/app/utils/PermChecker.js, admin-ui/plugins/auth-server/redux/features/scopeSlice.js, admin-ui/plugins/auth-server/redux/sagas/OAuthScopeSaga.js
=> fix(admin-ui): large header issue #1398

docs/install/docker-install/compose.md, docs/install/docker-install/quick-start.md, docs/install/helm-install/local.md, mkdocs.yml
=> Docs flex docker

docs/admin/admin-ui/userMgmt-menu.md
=> docs: add link to creation of user claims docs in Admin UI's User doc #1416

admin-ui/plugins/admin/redux/sagas/ApiPermissionSaga.js
=> fix(admin-ui): show error message on api failure

admin-ui/app/routes/Apps/Gluu/GluuSingleValueCompleter.js, admin-ui/plugins/admin/components/Mapping/MappingAddDialogForm.js
=> fix(admin-ui): remove input label

admin-ui/app/routes/Apps/Gluu/GluuAdvancedSearch.js, admin-ui/app/routes/Apps/Gluu/GluuInputRow.js
=> fix(admin-ui) : accepting character in number type fields #1437

docs/admin/recipes/getting-started-rancher.md, docs/install/helm-install/local.md
This is a PR to update the casa URI change from `/casa` to `/jans-casa`
=> fix(docs): update casa base URI

docs/admin/kubernetes-ops/upgrade.md, mkdocs.yml
=> docs: add k8s ops upgrade guide

charts/gluu-all-in-one/README.md, charts/gluu-all-in-one/templates/secret.yaml, charts/gluu-all-in-one/values.yaml, charts/gluu/charts/config/templates/secrets.yaml, charts/gluu/values.yaml
Remove unsupported custom salt from Helm chart.
Closes #1452
=> fix(comp-charts-flex): remove unsupported custom salt

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/plugins/admin/components/Permissions/PermissionAddDialogForm.js, admin-ui/plugins/admin/components/Permissions/UiPermDetailPage.js, admin-ui/plugins/admin/components/Permissions/UiPermListPage.js
=> feat(admin-ui): config api tag column #1444

flex-linux-setup/flex_linux_setup/flex_setup.py
jans app versio 1.0.21-SNAPSHOT
=> chore(flex-linux-setup): jans app versio 1.0.21-SNAPSHOT

docs/install/vm-install/vm-requirements.md
Adding Ubuntu 22 in VM requirement list
=> docs: flex update vm-requirements.md

admin-ui/.env.adminuitest, admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/package.json, admin-ui/plugins/auth-server/components/Clients/ClientEncryptionSigningPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
=> feat(admin-ui): the algorithm to secure the JWT for a particular introspection response #1409

admin-ui/app/routes/Dashboards/Chart/styles.css
=> fix(admin-ui): need to change the font color for Enabled header in the scripts grid #1472

admin-ui/app/routes/Apps/Gluu/GluuInlineInput.js, admin-ui/build/webpack.config.client.dev.js, admin-ui/build/webpack.config.client.prod.js, admin-ui/package.json, admin-ui/plugins/auth-server/components/Configuration/ConfigPage.js, admin-ui/plugins/auth-server/components/Configuration/JsonPropertyBuilder.js
=> fix(admin-ui): use yaml configs for auth server properties configuration #1475

admin-ui/app/redux/features/attributesSlice.js, admin-ui/app/redux/sagas/AttributesSaga.js, admin-ui/plugins/auth-server/redux/features/scopeSlice.js, admin-ui/plugins/auth-server/redux/sagas/OAuthScopeSaga.js
=> fix(admin-ui): remove generation of specific access_token #1477

admin-ui/app/redux/features/licenseDetailsSlice.js, admin-ui/app/redux/sagas/LicenseDetailsSaga.js, admin-ui/app/routes/Dashboards/DashboardPage.js, admin-ui/app/routes/Dashboards/styles.js, admin-ui/app/routes/License/LicenseDetailsPage.js, admin-ui/app/utils/Util.js
=> chore(admin-ui): displaying license details #1481

automation/startflexdemo.sh, automation/startflexmonolithdemo.sh
=> fix: command to External/LB IP

.github/workflows/activate-nightly-build.yml
Closes #1491 
This addressed the nightly build release naming issues
=> ci: fix nightly build calc

admin-ui/plugins/auth-server/components/Configuration/JsonPropertyBuilder.js
=> fix(admin-ui): auth server properties page crashes on visit #1506

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json
=> fix(admin-ui): change page header name to properties #1521

docs/supergluu/index.md
fixed the formatting to correctly display the bulleted list
=> fix(docs): fix bullet points format

docs/admin/admin-ui/logs.md
=> docs: admin-ui log location changed #1533

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/aui_webhook.ldif
=> feat(flex-linux-setup): admin-ui webhook changes

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
=> feat(admin-ui): export client summary in json format #1547

charts/gluu-all-in-one/templates/istio-gateway.yaml, charts/gluu/charts/cn-istio-ingress/templates/gateway.yaml
=> feat(flex): add support for passing custom istio gateways

docs/install/agama/prerequisites.md, docs/supergluu/admin-guide/index.md, mkdocs.yml
=> docs: update instructions for agama lab

admin-ui/.env, admin-ui/.env.adminuitest, admin-ui/.env.goldencrane, admin-ui/.env.test, admin-ui/.env.tmp, admin-ui/app/routes/Apps/Gluu/GluuSessionTimeout.js, admin-ui/build/webpack.config.client.dev.js, admin-ui/build/webpack.config.client.prod.js
=> feat(admin-ui): fetch sessionTimeout from config response #1575

docs/admin/admin-ui/admin-menu.md, docs/admin/admin-ui/configuration.md
=> docs: add documentation for admin-ui screen supporting editable UI configurations. #1582

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt, docker-admin-ui/scripts/bootstrap.py
Added session timeout for admin-ui.
Closes #1577
=> feat: add sessionTimeoutInMins in admin-ui configuration

admin-ui/app/redux/api/backend-api.js, admin-ui/app/redux/sagas/SagaUtils.js
=> fix(admin-ui): pass access token in /logging api #1581

flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> feat: add configurable additional parameters in admin-ui configuration #1594

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/redux/sagas/AuthSaga.js, admin-ui/app/routes/Apps/Gluu/GluuProperties.js, admin-ui/app/utils/AppAuthProvider.js, admin-ui/plugins/admin/components/Settings/SettingsPage.js
=> feat(admin-ui): add additional parameters in admin-ui config #1591

admin-ui/app/routes/Apps/Gluu/GluuProperties.js
update font-size of label & tooltip in properties component
=> chore(admin-ui): update font size of properties component

docker-admin-ui/Dockerfile, docker-admin-ui/templates/admin-ui/auiConfiguration.json
Add missing uiConfig attribute on fresh install.
Closes #1609
=> fix(docker-admin-ui): add missing uiConfig on fresh install

charts/gluu-all-in-one/README.md, charts/gluu-all-in-one/templates/cronjobs.yaml, charts/gluu-all-in-one/templates/deployment.yml, charts/gluu-all-in-one/values.yaml, docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt
Update images and charts to fix key-rotation issue in all-in-one setup.
Closes #1614
=> fix(charts): incorrect image for key-rotation job

admin-ui/app/routes/Apps/Gluu/GluuUploadFile.js, admin-ui/plugins/saml/components/SamlIdpForm.js, admin-ui/plugins/saml/components/TrustRelationForm.js, admin-ui/plugins/saml/redux/api/SamlApi.js
=> fix(admin-ui): show file name in edit saml page

admin-ui/app/utils/hooks/useWebhookDialogAction.js, admin-ui/openapi-merge.json, admin-ui/plugins/admin/components/Webhook/ShortcodePopover.js, admin-ui/plugins/admin/components/Webhook/WebhookForm.js, admin-ui/plugins/admin/components/Webhook/WebhookListPage.js, admin-ui/plugins/admin/helper/utils.js, admin-ui/plugins/admin/redux/sagas/WebhookSaga.js
=> fix(admin-ui): bugs in webhooks #1617

admin-ui/app/routes/Apps/Gluu/GluuInputEditor.js, admin-ui/plugins/admin/components/Webhook/WebhookForm.js, admin-ui/plugins/admin/helper/shortCodes.json
=> fix: improvements required in webhook shortcode #1624

docker-admin-ui/Dockerfile, docker-admin-ui/requirements.txt
Update image dependencies.
Closes #1639
=> chore(deps): sync image assets and dependencies

charts/gluu/charts/auth-server/templates/_helpers.tpl, charts/gluu/charts/auth-server/templates/deployment.yml, charts/gluu/charts/casa/templates/_helpers.tpl, charts/gluu/charts/casa/templates/deployment.yaml, charts/gluu/charts/config-api/templates/_helpers.tpl, charts/gluu/charts/config-api/templates/deployment.yaml, charts/gluu/charts/fido2/templates/_helpers.tpl, charts/gluu/charts/fido2/templates/deployment.yml, charts/gluu/charts/link/templates/_helpers.tpl, charts/gluu/charts/link/templates/deployment.yaml, charts/gluu/charts/saml/templates/_helpers.tpl, charts/gluu/charts/saml/templates/deployment.yaml, charts/gluu/charts/scim/templates/_helpers.tpl, charts/gluu/charts/scim/templates/deployment.yml, charts/gluu/values.yaml
=> feat: add java memory arguments

admin-ui/plugins/admin/components/CustomScripts/CustomScriptForm.js
=> fix(admin-ui): pass udpated value of custom script editor #1646

docker-flex-monolith/flex-ldap-compose.yml, docker-flex-monolith/flex-mysql-compose.yml, docker-flex-monolith/flex-postgres-compose.yml
Monolith image version has been updated in Compose files.
Closes #1654
=> fix(monolith): update monolith version in compose files

charts/gluu-all-in-one/templates/_helpers.tpl, charts/gluu-all-in-one/templates/nginx-ingress.yaml
=> fix(flex-aio): adjust config-api port and deploy kc

admin-ui/plugins/schema/components/Person/AttributeForm.js, admin-ui/plugins/schema/redux/sagas/AttributeSaga.js
=> bug(admin-ui): unable to deactivate custom validation #1650

admin-ui/plugins/services/Components/Configuration/CacheInMemory.js, admin-ui/plugins/services/Components/Configuration/CacheMemcached.js, admin-ui/plugins/services/Components/Configuration/CacheNative.js, admin-ui/plugins/services/Components/Configuration/CacheRedis.js
=> fix(admin-ui): unable to update Cache Configuration #1664

docker-admin-ui/Dockerfile
Sync upstream assets and configuration into CN images.
Closes #1667
=> chore(docker): sync assets and config

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Profile/ProfilePage.js, admin-ui/plugins/admin/helper/shortCodes.json, admin-ui/plugins/user-management/__tests__/api/Users.test.js, admin-ui/plugins/user-management/components/UserManagement/UserAddPage.js, admin-ui/plugins/user-management/components/UserManagement/UserEditPage.js, admin-ui/plugins/user-management/components/UserManagement/UserForm.js
=> fix(admin-ui): user status not showing active #1671

charts/gluu-all-in-one/templates/deployment.yml, charts/gluu/charts/config/templates/load-init-config.yml, docker-admin-ui/requirements.txt
=> fix: add cb-pass volume and update jans-pycloudlib

flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat(flex-linux-setup): no oidc client registration

admin-ui/app/routes/Apps/Gluu/GluuCommitDialog.js, admin-ui/app/routes/Apps/Gluu/GluuSelectRow.js, admin-ui/app/routes/Apps/Gluu/GluuToogle.js, admin-ui/app/routes/Apps/Gluu/GluuToogleRow.js, admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js, admin-ui/plugins/admin/components/Permissions/UiPermDetailPage.js, admin-ui/plugins/admin/components/Permissions/UiPermListPage.js, admin-ui/plugins/admin/components/Roles/UiRoleListPage.js, admin-ui/plugins/auth-server/components/Clients/ClientListPage.js, admin-ui/plugins/auth-server/components/Scopes/ScopeListPage.js, admin-ui/plugins/auth-server/components/Sessions/SessionListPage.js, admin-ui/plugins/jans-link/components/Tabs/ConfigurationTab.js
=> fix(admin-ui):performance issues on API roles pages, API permissions pages

admin-ui/plugins/auth-server/components/Agama/AgamaListPage.js, admin-ui/plugins/auth-server/components/AuthN/AuthNListPage.js, admin-ui/plugins/schema/components/Person/AttributeListPage.js, admin-ui/plugins/services/Components/Configuration/CacheNative.js, admin-ui/plugins/user-management/components/UserManagement/UserList.js
=> fix(admin-ui): Fix error on the below pages

admin-ui/app/redux/features/initSlice.js, admin-ui/plugins/admin/redux/features/WebhookSlice.js, admin-ui/plugins/admin/redux/features/customScriptSlice.js, admin-ui/plugins/saml/components/SamlIdentityList.js, admin-ui/plugins/saml/redux/features/SamlSlice.js, admin-ui/plugins/schema/redux/features/attributeSlice.js
=> fix(admin-ui): getting blank page for identity broker page

docker-admin-ui/Dockerfile, docker-flex-all-in-one/Dockerfile, docker-flex-all-in-one/app/requirements.flex.txt
Change the way Python is installed according to PEP 668.
Closes #1715
=> refactor(cloud-native): revisit Python libs installation method

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/plugins/saml/components/SamlIdpForm.js
=> feat(admin-ui): principalAttribute and principalType for SAML TR #1713

admin-ui/app/index.html, admin-ui/app/redux/api/axios.js, admin-ui/app/redux/api/base.js, admin-ui/app/redux/api/index.js, admin-ui/env-config.js, admin-ui/plugins/admin/components/Settings/SettingsPage.js, admin-ui/plugins/services/redux/api/index.js
=> feat: injecting env properties dynamically in admin-ui built #1720

charts/gluu/values.schema.json
The `values.schema.json` is re-formatted to use 4 spaces indentation.
Closes #1711
=> chore(charts): reformat values.schema.json for readability

automation/startflexdemo.sh
=> fix: allow version pass to avoid latest install always

docker-admin-ui/Dockerfile, docker-admin-ui/README.md, docker-admin-ui/requirements.txt, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/scripts/builder.py, docker-admin-ui/templates/admin-ui/env, docker-admin-ui/templates/admin-ui/env-config.js, docker-admin-ui/templates/admin-ui/nginx-default.conf, docker-flex-all-in-one/Dockerfile, docker-flex-all-in-one/app/requirements.flex.txt, docs/reference/kubernetes/docker-admin-ui.md
The changesets allow container to re-use pre-built admin-ui app.
Ref: https://github.com/GluuFederation/flex/issues/1725
=> chore(cloud-native): reuse pre-built admin-ui app

charts/gluu-all-in-one/templates/cronjobs.yaml
=> fix(charts): resolve overlapping cronjobs

admin-ui/plugins/admin/components/CustomScripts/CustomScriptDetailPage.js, admin-ui/plugins/user-management/components/UserManagement/UserDetailViewPage.js
=> fix(admin-ui): user details table in user management #1745

charts/gluu-all-in-one/templates/_helpers.tpl, charts/gluu-all-in-one/templates/deployment.yml, charts/gluu-all-in-one/templates/secret.yaml, charts/gluu/charts/config/templates/_helpers.tpl, charts/gluu/charts/config/templates/load-init-config.yml, charts/gluu/charts/config/templates/secrets.yaml, docker-admin-ui/Dockerfile, docker-flex-all-in-one/Dockerfile
Conform to new configuration schema of Janssen cloud-native.
Closes #1771
=> feat(cloud-native): modify images to conform to configuration schema

charts/gluu/charts/auth-server/templates/deployment.yml, charts/gluu/charts/casa/templates/deployment.yaml, charts/gluu/charts/config-api/templates/deployment.yaml, charts/gluu/charts/fido2/templates/deployment.yml, charts/gluu/charts/link/templates/deployment.yaml, charts/gluu/charts/saml/templates/deployment.yaml, charts/gluu/charts/scim/templates/deployment.yml
=> fix(charts): pass correct indentation

docker-admin-ui/Dockerfile, docker-admin-ui/Makefile, docker-admin-ui/requirements.txt, docker-flex-all-in-one/Dockerfile, docker-flex-all-in-one/Makefile
Upgrade Alpine OS to v3.20.
Closes #1784
=> feat(cloud-native): upgrade Alpine OS to v3.20

charts/gluu-all-in-one/README.md, charts/gluu-all-in-one/templates/nginx-ingress.yaml, charts/gluu-all-in-one/values.yaml, charts/gluu/README.md, charts/gluu/charts/nginx-ingress/templates/ingress.yaml, charts/gluu/values.yaml, docker-admin-ui/Dockerfile, docker-flex-all-in-one/Dockerfile
=> feat(jans-lock): add jans-lock ingress

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/app/routes/Apps/Gluu/GluuAppSidebar.js, admin-ui/plugins/admin/components/Settings/SettingsPage.js
closes [1801](https://github.com/GluuFederation/flex/pull/1801)
=> feat(admin-ui): Display current flex version in admin's setting page.

docker-admin-ui/Dockerfile, docker-admin-ui/scripts/bootstrap.py, docker-admin-ui/scripts/wait.py, docker-flex-all-in-one/Dockerfile
Added support for loading local configmaps and/or secrets.
Closes #1804
=> feat(cloud-native): add support reading configuration from file

admin-ui/app/routes/Apps/Gluu/GluuTypeAheadForDn.js, admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js
closes [1809](https://github.com/GluuFederation/flex/issues/1809)
=> Admin UI issue 1809

charts/gluu-all-in-one/templates/cronjobs.yaml, charts/gluu-all-in-one/templates/deployment.yml, charts/gluu-all-in-one/templates/secret.yaml, charts/gluu/charts/admin-ui/templates/deployment.yml, charts/gluu/charts/auth-server-key-rotation/templates/cronjobs.yaml, charts/gluu/charts/auth-server/templates/deployment.yml, charts/gluu/charts/casa/templates/deployment.yaml, charts/gluu/charts/config-api/templates/deployment.yaml, charts/gluu/charts/config/templates/load-init-config.yml, charts/gluu/charts/config/templates/secrets.yaml, charts/gluu/charts/fido2/templates/deployment.yml, charts/gluu/charts/kc-scheduler/templates/cronjobs.yaml, charts/gluu/charts/link/templates/deployment.yaml, charts/gluu/charts/opendj/templates/cronjobs.yaml, charts/gluu/charts/opendj/templates/statefulset.yaml, charts/gluu/charts/persistence/templates/jobs.yml, charts/gluu/charts/saml/templates/deployment.yaml, charts/gluu/charts/scim/templates/deployment.yml
The changeset reduces mounted files for persistence-related assets.
=> feat(charts): reduce mounted password files for persistence

admin-ui/plugins/auth-server/components/Clients/ClientBasicPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientCibaParUmaPanel.js, admin-ui/plugins/auth-server/components/Clients/ClientScriptPanel.js
closes [1828](https://github.com/GluuFederation/flex/issues/1828)
=> fix(admin-ui): unable to add scope in client

docs/install/vm-install/vm-requirements.md
=> doc: Update hardware requirement

docker-admin-ui/Dockerfile, docker-admin-ui/README.md, docker-admin-ui/scripts/wait.py, docker-flex-all-in-one/Dockerfile, docker-flex-monolith/Dockerfile, docs/reference/kubernetes/docker-admin-ui.md
The changeset sync assets and update dependencies.
Closes #1844
=> chore(cloud-native): sync assets and dependencies

admin-ui/plugins/auth-server/components/Configuration/ConfigApiConfiguration/ApiConfigForm.js
closes [1864](https://github.com/GluuFederation/flex/issues/1864)
=> fix(admin-ui): unable to update config-api-properties

admin-ui/app/routes/Apps/Gluu/GluuAdvancedSearch.js, admin-ui/app/routes/Apps/Gluu/GluuCustomScriptSearch.js, admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js, admin-ui/plugins/auth-server/components/Clients/ClientListPage.js, admin-ui/plugins/auth-server/components/Scopes/ScopeListPage.js, admin-ui/plugins/schema/components/Person/AttributeListPage.js, admin-ui/plugins/user-management/components/UserManagement/UserList.js
=> feat: search records should work on entering query and pressing enter… #1871

charts/gluu-all-in-one/templates/cronjobs.yaml, charts/gluu-all-in-one/values.yaml
=> fix(kc-scheduler): add missing customCommand in gluu-aio

admin-ui/app/locales/en/translation.json, admin-ui/app/locales/fr/translation.json, admin-ui/app/locales/pt/translation.json, admin-ui/plugins/smtp-management/components/SmtpManagement/SmtpForm.js, admin-ui/plugins/smtp-management/components/SmtpManagement/StmpEditPage.js, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> feat: adding ability to upload keystore in SMTP configuration form #1866

admin-ui/plugins/admin/components/Assets/AssetForm.js
=> fix(admin-ui): unable to add asset without adding description

admin-ui/plugins/auth-server/components/Clients/ClientBasicPanel.js
closes[https://github.com/GluuFederation/flex/issues/1899](1899)
=> fix(admin-ui): unable to select search scope 

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): removal of jans setup files

admin-ui/app/components/Layout/LayoutContent.js, admin-ui/app/components/SidebarMenu/SidebarMenuItem.js, admin-ui/app/layout/components/SidebarMiddleNav.js, admin-ui/app/redux/sagas/SagaUtils.js, admin-ui/app/routes/Apps/Gluu/GluuAppSidebar.js, admin-ui/app/routes/Apps/Gluu/GluuRemovableInputRow.js, admin-ui/app/routes/Apps/Gluu/GluuRemovableSelectRow.js, admin-ui/app/routes/Apps/Gluu/GluuRemovableTypeAhead.js, admin-ui/app/routes/Apps/Gluu/GluuSessionTimeout.js, admin-ui/app/routes/Dashboards/styles.js, admin-ui/app/routes/components/Dropdowns/DropdownProfile.js, admin-ui/app/utils/TokenController.js, admin-ui/plugins/user-management/components/UserManagement/UserClaimEntry.js, admin-ui/plugins/user-management/components/UserManagement/UserEditPage.js, admin-ui/plugins/user-management/components/UserManagement/UserForm.js, admin-ui/plugins/user-management/redux/features/userSlice.js, admin-ui/plugins/user-management/redux/sagas/UserSaga.js
closes [1908]( https://github.com/GluuFederation/flex/issues/1908)
=> fix(admin-ui): the audit log not reporting the required events

automation/startopenabankingdemo.sh, docs/install/helm-install/local.md, docs/openbanking/install-cn.md
=> fix(openbanking): update the script to use the latest values.yaml 

admin-ui/app/redux/features/logoutSlice.js, admin-ui/app/routes/Pages/ByeBye.js, admin-ui/app/routes/Pages/ProtectRoutes.js, admin-ui/app/routes/index.js, admin-ui/app/utils/AppAuthProvider.js
closes [1929](https://github.com/GluuFederation/flex/issues/1929)
=> feat(admin-ui): logout not working

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> feat: using agama_io.jans.casa.authn.main as default acr in admin-ui

admin-ui/app/routes/Apps/Gluu/GluuAdvancedSearch.js
closes [1912](https://github.com/GluuFederation/flex/issues/1912)
=> fix(admin-ui): search is not working properly

admin-ui/plugins/auth-server/components/Clients/ClientActiveTokens.js
closes [1947](https://github.com/GluuFederation/flex/issues/1947)
=> fix(admin-ui): filter is not working on pagination in client active token list.

admin-ui/plugins/user-management/components/UserManagement/UserAddPage.js, admin-ui/plugins/user-management/components/UserManagement/UserForm.js, admin-ui/plugins/user-management/components/UserManagement/UserList.js, admin-ui/plugins/user-management/redux/sagas/UserSaga.js
closes [1958](https://github.com/GluuFederation/flex/issues/1958)
=> fix(admin-ui): password should be hidden in audit logs. 

admin-ui/app/routes/Apps/Gluu/GluuRemovableSelectRow.js, admin-ui/plugins/auth-server/components/Scopes/ScopeAddPage.js, admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js
closes [1965](https://github.com/GluuFederation/flex/issues/1965)
=> fix(admin-ui): unable to add country claim in Users form.

admin-ui/plugins/auth-server/components/Agama/AgamaListPage.js
closes [1970](https://github.com/GluuFederation/flex/issues/1970)
=> fix(admin-ui): agama projects are not deploying properly

admin-ui/plugins/schema/components/Person/AttributeForm.js
closes [1986](https://github.com/GluuFederation/flex/issues/1986)
=> fix(admin-ui): Organziation attributes are not updating.

admin-ui/.env, admin-ui/.gitignore
=> fix(admin-ui): unable to open Admin UI

docs/solo/solo-administration-guide.md, docs/solo/solo-getting-started.md, docs/solo/solo-subscription.md
Removing `coming soon` note from the header section of all the Solo docs
=> fix(docs):  remove `coming soon` note from the Solo docs

docker-admin-ui/Dockerfile, docker-admin-ui/scripts/bootstrap.py
The changeset adds new config to sync license details.
Closes #2017
=> feat(docker-admin-ui): add configuration to set interval to sync license details

admin-ui/plugins/user-management/components/UserManagement/UserDetailViewPage.js
What is in the PR
=============
Fixing the inconsistency of showing an array / multivalued custom attribute on the user management list.
=> fix(admin-ui): fix showing user custom attributes

admin-ui/plugins/auth-server/components/Ssa/SsaAddPage.js
What is in the PR
=============
Fix unable to save SSA
fix: #2039
=> fix(admin-ui): fix get time for expired date

automation/startflexmonolithdemo.sh, docker-flex-monolith/Dockerfile
The changeset set `FLEX_BUILD_COMMIT` default to `main`.
Closes #2054
=> chore(cloud-native): set default FLEX_BUILD_COMMIT in demo scripts

admin-ui/app/routes/Apps/Gluu/GluuFormActionRow.js, admin-ui/package.json, admin-ui/plugins/auth-server/components/JsonViewer/JsonViewer.css, admin-ui/plugins/auth-server/components/JsonViewer/JsonViewer.js, admin-ui/plugins/auth-server/components/JsonViewer/JsonViewerDialog.js, admin-ui/plugins/auth-server/components/Ssa/SsaDetailPage.js, admin-ui/plugins/auth-server/components/Ssa/SsaListPage.js
https://github.com/GluuFederation/flex/issues/2063
closes #2063
=> feat(admin-ui): add download/view feature in SSA page of Admin UI

admin-ui/plugins/auth-server/components/JsonViewer/JsonViewerDialog.js, admin-ui/plugins/auth-server/components/Ssa/SsaListPage.js, admin-ui/plugins/auth-server/redux/api/SsaApi.js, admin-ui/plugins/auth-server/redux/features/SsaSlice.js, admin-ui/plugins/auth-server/redux/sagas/SsaSaga.js
=> feat(admin-ui): Downloaded SSA should be in a jwt file

docs/install/vm-install/ubuntu.md
update flex for ubuntu24 os document
closes#2088
=> Update ubuntu.md for ubuntu24

docker-admin-ui/templates/admin-ui/clients.ldif, flex-linux-setup/flex_linux_setup/flex_setup.py
=> feat: admin ui web OIDC client should be set to generate the access_token in JWT format by default

flex-linux-setup/flex_linux_setup/flex_setup.py, flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json
=> feat(flex-linux-setup): sync AdminUI scopes

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): bugs in client creation

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup):  Admin UI Web Client URIs

admin-ui/README.md
=> fix: remove airframe note

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): add jansAccessTknLife for adminui clients

flex-linux-setup/flex_linux_setup/flex_setup.py
=> fix(flex-linux-setup): changes required in Admin UI Web Client

admin-ui/app/routes/Apps/Gluu/GluuInlineInput.tsx
https://github.com/GluuFederation/flex/issues/2259
closes #2259
=> fix(admin-ui): add null check validation in Auth Server Configuration page

.github/workflows/build-packages.yml, docker-admin-ui/Dockerfile, docker-flex-all-in-one/Dockerfile, docker-flex-monolith/Dockerfile
=> chore: update source versions
