docker-casa/scripts/auth_conf.py
docker-casa/scripts/entrypoint.sh

The changeset enable pulling `otp_configuration.json` and `super_gluu_creds.json` from secrets layer as complement for https://github.com/JanssenProject/jans/pull/784

feat(image): pull otp and super_gluu configuration from secrets

---

flex-linux-setup/flex_linux_setup/flex_setup.py

With this PR, `flex_setup.py` can use jans installer at `/opt/jans/jans-setup/` and can run without packaging

fix: flex-linux-setup able to use existing jans-setup to be used as standalone script

---

casa/pom.xml

Sonarcloud project ID needed to be in correct case. Camel case. 
I also added `flex` as it would otherwise clash with existing casa project id in sonarcloud.

ci: fix sonarcloud project id for casa

---

.github/CODEOWNERS

Upon a request from @duttarnab , @mjatin-dev has been added to the codeowners of admin-ui

ci: add codeowner

---

docker-casa/Dockerfile
docker-casa/jetty/casa.xml
docker-casa/jetty/log4j2.xml
docker-casa/scripts/bootstrap.py
docker-casa/scripts/entrypoint.sh

Overview:
- use `casa.war` instead of exploded war to avoid hot-deployment issue
- update `casa.war` source (contains fix with logging)
- sync `log4j2.xml`

chore: sync casa image

---

docker-casa/scripts/bootstrap.py
docker-casa/scripts/entrypoint.sh

The following jetty arguments are passed via command-line (entrypoint):
- `jetty.httpConfig.sendServerVersion=false` to disable server info
- `jetty.deploy.scanInterval=0` to disable hot-deployment

refactor: set arguments for jetty via command-line

---

admin-ui/app/routes/Apps/Gluu/GluuCustomScriptSearch.js
admin-ui/plugins/admin/components/CustomScripts/CustomScriptForm.js
admin-ui/plugins/admin/components/CustomScripts/ScriptListPage.js
admin-ui/plugins/admin/components/CustomScripts/scriptTypes.js

[… ](https://github.com/GluuFederation/flex/issues/155)

fix: scriptType dropdowns is not working perfectly in Script-List and Add Script page #155

---

admin-ui/app/colors.js
admin-ui/app/components/Avatar/Avatar.js
admin-ui/app/components/Avatar/AvatarImage.js
admin-ui/app/components/EmptyLayout/EmptyLayoutSection.js
admin-ui/app/components/FloatGrid/Col.js
admin-ui/app/components/FloatGrid/Row.js
admin-ui/app/components/HolderProvider/HolderTextProvider.js
admin-ui/app/components/InputGroupAddon/InputGroupAddon.js
admin-ui/app/components/Layout/Layout.js
admin-ui/app/components/Layout/setupPage.js
admin-ui/app/components/OuterClick/OuterClick.js
admin-ui/app/components/SidebarMenu/SidebarMenu.js
admin-ui/app/components/Theme/ThemeSelector.js
admin-ui/app/components/UncontrolledTabs/UncontrolledTabsNavLink.js
admin-ui/app/components/Wizard/Wizard.js
admin-ui/app/routes/Layouts/DragAndDropLayout/DragAndDropLayout.js
admin-ui/app/routes/components/Analytics/TinyAreaChart.js
admin-ui/app/routes/components/Analytics/TinyAreaChartSpend.js
admin-ui/app/routes/components/Analytics/TrTableTrafficChannels.js
admin-ui/app/routes/components/Colors/CardRgbaColor.js
admin-ui/app/routes/components/Financial/TrTableInvoices.js
admin-ui/app/routes/components/Financial/TrTableRecentFundings.js
admin-ui/app/routes/components/Monitor/TrTableMonitor.js
admin-ui/app/routes/components/Stock/TrTableFavStock.js
admin-ui/app/routes/components/Stock/TrTableStock.js
admin-ui/app/routes/components/Stock/TrTableSummary.js
admin-ui/app/routes/components/VersionSelector.js

Update code that uses import lodash library to be
1. More readable 
2. Reduce import size
1. If only import <= 3 function in the file then use, import specific `import map from 'lodash/map'`
It will reduce import size significantly and also got clean and more readable code 
2. If importing more than 3 functions the use import function one by one, `import { map, reduce, isEmpty, max } from 'lodash'`
It will reduce import size and also got clean and more readable code 
Signed-off-by: Harry Andriyan <harry.andriyan@gmail.com>

feat(lodash): update lodash import to be more readable and smaller

---

admin-ui/app/components/App/AppMain.js
admin-ui/app/redux/store/index.js
admin-ui/package.json

- Development target issue
We recommend using the `configureStore` method of the @reduxjs/toolkit package, to replaces `createStore`.
Redux Toolkit is our recommended approach for writing Redux logic today, including store setup, reducers, data fetching, and more.
Replace `createStore` with `configureStore` and make sure all functionality still 100% properly working

feat(redux store): update deprecated createStore

---

docker-admin-ui/Dockerfile
docker-admin-ui/README.md
docker-admin-ui/requirements.txt
docker-admin-ui/scripts/bootstrap.py
docker-admin-ui/scripts/wait.py
docker-casa/Dockerfile
docker-casa/README.md
docker-casa/requirements.txt
docker-casa/scripts/bootstrap.py
docker-casa/scripts/wait.py

The changeset introduces new hybrid persistence mapping as seen in https://github.com/JanssenProject/jans/issues/680 and https://github.com/JanssenProject/jans/pull/1505

feat: introduce new hybrid persistence mapping

---

flex-linux-setup/flex_linux_setup/flex_setup.py

Provide arfuments for Janssen Installer. For example:
` python3 flex_setup.py --jans-installer-args="-f /root/setup.properties -n -c"`

feat: flex-linux-setup jans installer args

---

flex-linux-setup/README.md
flex-linux-setup/flex_linux_setup/flex_setup.py

In this PR
1) Install flex with setup properties with command `python3 flex_setup.py -f /path/to/setup.properties -n -c`
2) Save setup.properties.last after installing flex to include casa related properties
3) Update document for automating installation with setup.properties

refactor: Flex Linux Setup install with properties file

---

.github/workflows/docker_build_image.yml
docker-casa/.hadolint.yaml
docker-casa/Dockerfile
docker-casa/Makefile

Overview:
Previously, `lxml` (v4.8.0) is installed from Alpine 3.16 repo.
By removing the package, `lxml` is now installed via `pip` (as direct dependency of `webdavclient3` library).
Misc: update `Makefile` and `hadolint` config

fix(docker-casa): upgrade lxml version

---

admin-ui/app/routes/Dashboards/DashboardPage.js

Update dashboard count of Actives Users & Access Token Stats not shown after loading finished

feat(admin-ui): update dashboard count summary not shown

---

docker-admin-ui/Dockerfile
docker-admin-ui/Makefile
docker-casa/Dockerfile
docker-casa/Makefile

The changeset applies security updates to the following components:
* upgrade Alpine to v3.16.1
* upgrade Liberica JRE to v11.0.16
* upgrade Jetty to v11.0.11
* upgrade Alpine to v3.16.1
* change base image to node:14.20-alpine3.16 for seamless updates
* remove vulnerable Java JAR file (included in openapitools/openapi-generator-cli) after installation
* set security-checks=vuln to Trivy scanner

chore(images): apply security updates to docker images

---

docker-admin-ui/templates/clients.ldif
flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config/templates/upgrade-ldap-101-jans.yaml
flex-linux-setup/flex_linux_setup/templates/casa_client.ldif

The changeset removes `jansRequireAuthTime` attribute to address issue #360.

chore: remove jansRequireAuthTime attribute of clients

---

admin-ui/plugins/auth-server/components/Clients/ClientShowSpontaneousScopes.js

https://github.com/GluuFederation/flex/issues/357

fix(admin-ui): show id for scopes in client edit page

---

admin-ui/app/routes/Dashboards/DashboardPage.js

The user-info and server status cards are overlapping on the desktop.

fix(admin-ui): dashboard card overlapping

---

admin-ui/app/redux/reducers/LogoutReducer.js
admin-ui/app/routes/Apps/Gluu/LanguageMenu.js

Admin UI should remember language and theme config after user logout
Steps: 
1. Log in to admin-ui.
2. Select a different theme and language
3. Log out
4. Re-login
5. The admin-ui again shows default theme and language
Expected:
The admin-ui should remember the theme and language selected last time by user and should set it everytime the user logs in.

feat(admin-ui): remember languange and theme config after user logout

---

flex-linux-setup/flex_linux_setup/flex_setup.py

fix: flex-linux-setup python executable

---

flex-linux-setup/flex_linux_setup/flex_setup.py

fix: flex-linux-setup noninteractive setup

---

admin-ui/.eslintrc.js
admin-ui/package.json

The issue is because the package we are using is deprecated. Update with the latest one.
Updated Package link : https://www.npmjs.com/package/@babel/eslint-parser
https://github.com/GluuFederation/flex/issues/495

fix(admin-ui): Update ES lint plugin 

---

docker-admin-ui/Dockerfile
docker-admin-ui/requirements.txt

The changesets add `openapi-merge-cli` executable from NPM package.
Closes: #525

fix(image): add missing openapi-merge-cli executable

---

admin-ui/plugins/auth-server/components/Clients/ClientListPage.js
admin-ui/plugins/auth-server/redux/api/OIDCApi.js
admin-ui/plugins/auth-server/redux/sagas/OIDCSaga.js

Issue comes because of the response change and delete not working because of the JANS api name changed.
https://github.com/GluuFederation/flex/issues/519

fix(admin-ui): OIDC client delete fixed

---

admin-ui/plugins/auth-server/components/Configuration/Defaults/LoggingPage.js

Fixing failed to save logging configuration
Steps to reproduce: 
1. Save the changed logging details.
2. Go to another page then revisit the logging page.
3. The modified logging details are not saved.

feat(admin-ui): update logging params name

---

flex-linux-setup/flex_linux_setup/templates/auiConfiguration.properties

fix: flex-linux-setup use encoded client secret

---

flex-linux-setup/flex_linux_setup/flex_setup.py

fix: flex-linux-setup missing source_files definition for casa

---

admin-ui/plugins/auth-server/components/Scopes/ScopeForm.js

https://github.com/GluuFederation/flex/issues/573

fix: error in creating scope #573

---

flex-linux-setup/flex_linux_setup/flex-plugin.py

fix: jans-linux-setup flex-plugin install dir

---

docs/install/helm-install/digitalocean-dok.md
docs/install/helm-install/red-hat-open-shift.md
docs/install/setup.md
docs/install/vm-install/disa-stig.md
docs/install/vm-install/dynamic-download.md
docs/install/vm-install/rhel.md
docs/install/vm-install/suse.md
docs/install/vm-install/ubuntu.md
docs/install/vm-install/vm-requirements.md
mkdocs.yml

This PR adds a draft for Ubuntu 20 installation, removes some non-roadmapped pages, and contains some miscellaneous updates to install docs.

Docs: Filling in installation documentation

---

docker-casa/Dockerfile
docker-casa/scripts/entrypoint.sh

The changeset excludes Prometheus JMX exporter from image. The exporter will be downloaded (if necessary) in container-level.
Closes #685

chore(docker-casa): exclude optional prometheus exporter from images

---

docker-casa/Dockerfile
docker-casa/README.md
docker-casa/jetty/log4j2.xml
docker-casa/scripts/bootstrap.py
flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config/templates/configmaps.yaml
flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/values.yaml

The changeset introduces feature to enable prefix on `STDOUT` logging for casa.
Closes #690

feat(docker-casa): enable prefix and group for stdout logs

---

automation/docs/generate-property-docs.sh
casa/app/pom.xml
casa/config/pom.xml
casa/pom.xml
casa/shared/pom.xml
mkdocs.yml

This PR includes required changes so developers can auto-generate property and feature flag documentation using annotations. 
- Changes in this PR puts in place the infrastructure code
- Some of this code must be updated when developers add annotations first time to a module. Commentary has been added to indicate such places.

ci: add changes for property and feature flag doc generation

---

casa/config/pom.xml
casa/pom.xml

closes #748 
In order to integrate annotation processors for property documentation, `<annotationProcessors>` configuration element was added. This did not list `org.pf4j.processor.ExtensionAnnotationProcessor`.

fix: pf4j annotation processing

---

docker-casa/Dockerfile

The changeset adjusts permission for `/opt/jans/jetty/casa/resources` directory.
Closes #746

fix(docker-casa): adjust permission to allow creating administrable lock file

---

flex-linux-setup/flex_linux_setup/flex_setup.py

What is in the PR
=============
update `JANS_APP_VERSION` to `1.0.7`

chore(flex-linux-setup): adjust jans version, bump to 1.0.7

---

docker-casa/Dockerfile

Overview:
- update base image to `bellsoft/liberica-openjre-alpine:11.0.18`
- update casa WAR file
Closes #762

chore(docker-casa): update dependencies to reduce vulnerabilities

---

docs/install/vm-install/ubuntu.md

Download ubuntu packages to `/tmp` rather than `~`

fix(docs): ubuntu install download location

---

docker-casa/Dockerfile

Switching back to `GLUU_VERSION=5.0.0-SNAPSHOT` fixes the image build.
Closes #868

fix(docker-casa): image build failed due to mismatched version

---

.github/workflows/docker_build_image.yml
automation/auto_update_image_pr.py
docker-admin-ui/Dockerfile
docker-admin-ui/Makefile
docker-casa/Dockerfile
docker-casa/Makefile
docker-flex-monolith/Dockerfile
docker-flex-monolith/Makefile

The image labels are changed to OCI-compliant annotations.
Closes #870

chore(docker): update image labels to reflect ghcr migration

---

docker-admin-ui/Dockerfile
docker-admin-ui/Makefile
docker-casa/Dockerfile
docker-flex-monolith/Dockerfile

The changeset fixes incorrect LABEL syntax for image builds.
Closes #914

build(docker): incorrect label syntax prevent image builds

---

flex-linux-setup/flex_linux_setup/flex_setup.py

Stopping **casa** before uninstalling has been added:
Issue: https://github.com/GluuFederation/flex/issues/943.

fix: flex_setup: stopping casa before uninstalling has been added;

---

flex-linux-setup/flex_linux_setup/flex_setup.py

fix(flex-linux-setup): set redirect_uris as AS for client registration

---

docker-casa/Dockerfile

The changeset upgrades Jetty to 11.0.15 in Casa image.
Closes #972

chore(docker-jans): upgrade jetty to mitigate vulnerabilities

---

docker-admin-ui/Dockerfile
docker-admin-ui/README.md
docker-casa/Dockerfile
docker-casa/README.md

Overview:
- change home directory of running user to `/home/1000`
- remove `GOOGLE_APPLICATION_CREDENTIALS` env
- add new `$HOME/.config/gcloud` directory
Closes #982

fix: ensure google libs support all possible credentials

---

automation/startflexmonolithdemo.sh
docker-flex-monolith/.gitignore
docker-flex-monolith/Dockerfile
docker-flex-monolith/flex-ldap-compose.yml
docker-flex-monolith/flex-mysql-compose.yml
docker-flex-monolith/flex-postgres-compose.yml
docker-flex-monolith/scripts/entrypoint.sh

The following changes closes #992.
1. Add support for running processes using scripts under `/opt/dist/scripts` directory (for example: `/opt/dist/scripts/opendj start`)
2. allow build mode (instead of pulling image) only if `FLEX_BUILD_COMMIT` passed to `automation/startflexmonolithdemo.sh`

fix(docker-flex-monolith): unable to run processes due to offline systemd

---

flex-linux-setup/flex_linux_setup/flex_setup.py

When there is a newline after ssa jwt in a file, decoding fails. This PR closes #1032

fix(flex-linux-setup): strip ssa after read from file

---

docker-admin-ui/scripts/bootstrap.py
docker-admin-ui/scripts/ssa.py

The changeset sets SSA `org_id` as license hardware key.
Closes #1052

feat(docker-admin-ui): set org_id as licenseHardwareKey

---

admin-ui/app/routes/Apps/Gluu/GluuSessionTimeoutDialog.js

issue #1081
**Cause**
The `Button` component from mui, doesn't accept custom color, 
using `Button` from `reactstrap` will solve the issue with existing feature & preferred styles.

fix(admin-ui): session expiration dialog is not being displayed #1081

---

docker-admin-ui/Dockerfile

The changeset changes base images from `node:hydrogen-alpine` to `node:hydrogen-alpine3.17` for `py3-grpcio` compatibility.
Closes #1094

fix(docker-admin-ui): incompatible py3-grpcio version

---

flex-linux-setup/flex_linux_setup/flex_setup.py

fix(flex-linux-setup): read profile from existing jans setup

---

docker-admin-ui/Dockerfile
docker-admin-ui/Makefile

The changeset synchronizes assets from upstream.
Closes #1121

fix(docker-admin-ui): error activating license key due to outdated assets

---

flex-cn-setup/pygluu/kubernetes/templates/helm/gluu/charts/config/templates/configmaps.yaml

Duo script is deleted from Flex CN installation as per https://github.com/GluuFederation/flex/issues/1120.

chore(flex-cn-setup): remove duo script from flex

---

flex-linux-setup/flex_linux_setup/flex_setup.py

fix(flex-linux-setup): do not remove duo script after upgrade

---

docker-casa/jetty/log4j2.xml
docker-casa/scripts/bootstrap.py

The changeset sets namespaced context for `log.console.*` in `log4j2.xml`.
Closes #1240

refactor(docker): avoid context collision on custom log4j2.xml

---

docker-casa/Dockerfile
docker-casa/scripts/bootstrap.py

Overview:
1. remove script to modify `/opt/jetty/etc/webdefault.xml`.
2. modifying `/opt/jetty/etc/jetty.xml` is done at image-level ops.
Closes #1249

refactor(docker-casa): handle custom jetty.xml and webdefault.xml

---

docker-casa/Dockerfile
docker-casa/scripts/bootstrap.py

The changeset change the symlink to JVM (JRE).
Closes #1307

refactor(docker-casa): unify path to JVM cacert file

---

docker-casa/Dockerfile

The changeset updates Jetty to v11.0.16.
Closes #1320

fix(docker-casa): update jetty to v11.0.16

---

docker-admin-ui/Dockerfile
docker-admin-ui/templates/admin-ui/clients.ldif

The changeset updates admin-ui clients for Auth and Token servers.
Closes #1309

fix(docker-admin-ui): update admin-ui clients for auth using js lib

---

admin-ui/app/routes/Apps/Gluu/GluuTypeAheadForDn.js
admin-ui/app/styles/components/wizard.scss
admin-ui/plugins/auth-server/components/Clients/ClientAdvancedPanel.js
admin-ui/plugins/auth-server/components/Clients/ClientBasicPanel.js
admin-ui/plugins/auth-server/components/Clients/ClientCibaParUmaPanel.js
admin-ui/plugins/auth-server/components/Clients/ClientEncryptionSigningPanel.js
admin-ui/plugins/auth-server/components/Clients/ClientLogoutPanel.js
admin-ui/plugins/auth-server/components/Clients/ClientScriptPanel.js
admin-ui/plugins/auth-server/components/Clients/ClientSoftwarePanel.js
admin-ui/plugins/auth-server/components/Clients/ClientTokensPanel.js
admin-ui/plugins/auth-server/components/Clients/ClientWizardForm.js
admin-ui/plugins/auth-server/redux/features/oidcSlice.js
admin-ui/plugins/auth-server/redux/features/scopeSlice.js

closes #1341
changes includes
- UI improvements in add/edit client form screen
- fixed expirable client input field
- removed dead unused code in form
- fixed radio selection of Access token type & RPT token type fields
- use `formik` to display input values (this will help UI input elements to display input values even if there are changes in tab)

fix(admin-ui): save form value of client in state while navigating between tabs #1341

---

admin-ui/plugins/admin/redux/api/ScriptApi.js

testing `/script-types` endpoint using method `getCustomScriptType` instead of `getCustomScriptTypes`.

fix(admin-ui): use getCustomScriptType to fetch script-types

---

flex-linux-setup/flex_linux_setup/flex_setup.py
flex-linux-setup/flex_linux_setup/templates/auiConfiguration.json

feat(flex-linux-setup): replace jwt token with reference token to access config-api

---

docker-admin-ui/Dockerfile
docker-admin-ui/scripts/bootstrap.py
docker-admin-ui/scripts/entrypoint.sh
docker-admin-ui/scripts/ssa.py
docker-admin-ui/scripts/upgrade.py
docker-admin-ui/templates/admin-ui/auiConfiguration.json
docker-admin-ui/templates/admin-ui/clients.ldif

Changes for using reference token in docker-admin-ui.
Closes #1456

feat(docker-admin-ui): replace jwt token with reference token to access config-api

---

flex-linux-setup/flex_linux_setup/flex_setup.py

fix(flex-linux-setup): stop jans-auth and config-api before building admin-ui

---

flex-linux-setup/flex_linux_setup/flex_setup.py
flex-linux-setup/flex_linux_setup/templates/scopes.ldif

feat(flex-linux-setup): ssa scope for admin-ui client

---

docker-admin-ui/Dockerfile
docker-admin-ui/scripts/upgrade.py
docker-admin-ui/templates/admin-ui/clients.ldif

The changesets add `https://jans.io/auth/ssa.admin` scope to Admin UI Backend API client.
Closes #1524

chore(docker-admin-ui): add ssa.admin scope to Admin UI backend client

---

admin-ui/plugins/saml/components/SamlIdpForm.js

- addition to issue #1413, `realm` is added as mandatory field for IDP creation.

fix(admin-ui): make realm field mandatory #1413

---

docs/install/vm-install/vm-requirements.md

Straight VM deployments are for the dev and staging environments.
VM in production requires k8s, in which Rancher could be utilized.

docs: add note on dev and staging env and where we support production

---

admin-ui/app/routes/Apps/Gluu/GluuCommitDialog.js
admin-ui/app/routes/Apps/Gluu/GluuDialog.js
admin-ui/app/utils/hooks/useWebhookDialogAction.js

**Issue Explained**
Display webhook execution acceptance dialog only if webhook trigger endpoint permission exists. `jans-auth-server/config/adminui/webhook.readonly`
part of #1530

fix(admin-ui): get feature mapped webhooks on read permission

---

admin-ui/app/routes/Apps/Gluu/GluuRemovableInputRow.js
admin-ui/plugins/user-management/components/UserManagement/UserClaimEntry.js
admin-ui/plugins/user-management/components/UserManagement/UserEditPage.js
admin-ui/plugins/user-management/components/UserManagement/UserForm.js

fix(admin-ui): render switch for dataType boolean in user form #1544

---

docker-admin-ui/Dockerfile
docker-admin-ui/README.md
docker-admin-ui/requirements.txt
docker-admin-ui/scripts/bootstrap.py
docker-admin-ui/templates/admin-ui/auiConfiguration.json
docker-flex-all-in-one/Dockerfile
docker-flex-all-in-one/app/requirements.flex.txt
docker-flex-monolith/Dockerfile
docs/reference/kubernetes/docker-admin-ui.md

Sync assets and dependencies to address https://github.com/GluuFederation/flex/issues/1594

feat(docker): add configurable additional parameters in admin-ui configuration

---

admin-ui/plugins/user-management/redux/sagas/UserSaga.js

feat: enable dialog for password which is not following rule #1593

---

docs/includes/cn-system-requirements.md
docs/install/helm-install/amazon-eks.md
docs/install/helm-install/google-gke.md
docs/install/helm-install/local.md
docs/install/helm-install/microsoft-azure.md
mkdocs.yml

docs(system-requirements): update values centrally

---

admin-ui/app/routes/Apps/Gluu/GluuInputEditor.js
admin-ui/app/routes/Apps/Gluu/GluuPropertyItem.js
admin-ui/app/routes/Apps/Gluu/GluuTypeAhead.js
admin-ui/plugins/admin/components/Webhook/WebhookForm.js
admin-ui/plugins/admin/components/Webhook/WebhookListPage.js

fix(admin-ui): fix issues on Webhooks table and console warning

---

admin-ui/plugins/admin/components/Webhook/WebhookForm.js
admin-ui/plugins/admin/components/Webhook/WebhookURLChecker.js

feat(admin-ui): Implement security measures for webhook 

---

docker-admin-ui/Dockerfile
docker-admin-ui/requirements.txt
docker-flex-all-in-one/Dockerfile

Address the issue while sync assets in slow network environment.
Closes #1728

fix(cloud-native): resolve failure on sync assets using git

---

charts/gluu/charts/auth-server/templates/_helpers.tpl
charts/gluu/charts/casa/templates/_helpers.tpl
charts/gluu/charts/config-api/templates/_helpers.tpl
charts/gluu/charts/fido2/templates/_helpers.tpl
charts/gluu/charts/link/templates/_helpers.tpl
charts/gluu/charts/saml/templates/_helpers.tpl
charts/gluu/charts/scim/templates/_helpers.tpl
charts/gluu/values.yaml

The changesets modify memory allocation for Gluu chart.
Closes 1735

fix: charts java memory options passed

---

flex-linux-setup/flex_linux_setup/flex_setup.py
flex-linux-setup/flex_linux_setup/templates/env-config.js

feat(flex-linux-setup): use built archive for setup

---

admin-ui/plugins/user-management/redux/sagas/UserSaga.js

- closes #1723 
- changes
using `message` value from the api respones additionally with `description`.
Current api response on error:
```
{
"code": "500",
"message": "ERROR: duplicate key value violates unique constraint \"jansperson_uid_unique_idx\"\n  Detail: Key (uid)=(admin) already exists."
}
```

fix(admin-ui): display duplicate error on adding user #1723

---

docker-admin-ui/Dockerfile
docker-admin-ui/README.md
docker-admin-ui/scripts/bootstrap.py
docker-admin-ui/templates/admin-ui/auiConfiguration.json
docker-admin-ui/templates/admin-ui/env-config.js

Closes #1576 
Supersed https://github.com/GluuFederation/flex/pull/1682

feat: implement a method to override the default connection params for the admin-ui

---

charts/gluu-all-in-one/templates/secret.yaml

Fixed incorrect data type of `optional_scopes`.
Closes #1777

fix(charts): incorrect data type passed as optional_scopes input

---

docker-flex-monolith/Dockerfile

Added missing `ruamel.yaml` library inside monolith OCI image.
Closes #1824

fix(monolith): resolve missing ruamel.yaml library inside monolith OCI image

---

docker-admin-ui/Dockerfile
docker-admin-ui/scripts/upgrade.py
docker-flex-all-in-one/Dockerfile

closes #1872 
The changeset adds support for legacy and new simple JSON data format using auto-detection of column's value.
**How to test:**
1. Flex 5.1.5 and lower:
- install flex 5.1.5 chart; ensure format `jansAppConf.jansSmtpConf` value is `{"v": []}`
- upgrade to chart in this PR (change jans image to `1.1.6_json` and flex image to `5.1.6`); ensure format `jansAppConf.jansSmtpConf` value is still `{"v": []}` after upgrade
1. Flex 5.1.6+:
- install chart in this PR (change jans image to `1.1.6_json` and flex image to `5.1.6_json`); ensure format `jansAppConf.jansSmtpConf` value is `[]`
- do upgrade; ensure format `jansAppConf.jansSmtpConf` value is still `[]` after upgrade

feat(cloud-native): add support for legacy and simple JSON data

---

docker-admin-ui/Dockerfile
docker-admin-ui/README.md
docker-admin-ui/scripts/bootstrap.py
docker-admin-ui/scripts/upgrade.py
docker-flex-all-in-one/Dockerfile
docker-flex-monolith/Dockerfile

The changeset removes spanner support from OCI images.
Closes #1879

chore(cloud-native)!: remove spanner support from OCI images

---

admin-ui/app/locales/en/translation.json
admin-ui/app/locales/fr/translation.json
admin-ui/app/locales/pt/translation.json
admin-ui/app/routes/License/LicenseDetailsPage.js

fix: lic details page showing error 'The License API is not enabled for this application.' #1892

---

docker-admin-ui/Dockerfile
docker-admin-ui/scripts/upgrade.py

The changeset removes calls to non-existent functions in jans-pycloudlib.
Closes #1896

fix(docker-admin-ui): remove non-existent function calls

---

automation/docs/generated-cn-docs.sh
automation/janssen_helm_chart/prepare_chart.sh
automation/release/release.sh

The changeset adds `--skip-version-footer` option when running `helm-docs` command.
Closes #1924

ci(automation): skip generating version footer when using helm-docs

---

docker-admin-ui/Dockerfile
docker-flex-all-in-one/Dockerfile

The changeset synchronizes assets and dependencies of OCI images.
Closes #1945

chore(cloud-native): sync assets to OCI images

---

admin-ui/app/locales/en/translation.json
admin-ui/app/locales/fr/translation.json
admin-ui/app/locales/pt/translation.json
admin-ui/app/routes/Apps/Gluu/GluuPermissionModal.js
admin-ui/app/routes/Dashboards/DashboardPage.js

closes [1952](https://github.com/GluuFederation/flex/issues/1952)

fix(admin-ui): update token script should reject the tampered user-info-jwt

---

admin-ui/app/locales/en/translation.json
admin-ui/app/locales/fr/translation.json
admin-ui/app/locales/pt/translation.json
admin-ui/plugins/admin/components/Roles/UiRoleListPage.js

closes [1795](https://github.com/GluuFederation/flex/issues/1795)

fix(admin-ui): message not correct while creating duplicate role

---

flex-linux-setup/flex_linux_setup/flex_setup.py

Closes #477
Instead of properties file, setting application versions via argument is more convenient.
You can provide three arguments. Example
`python3 flex_setup.py --jans-app-verison=1.1.6 --jans-build="-SNAPSHOT" --node-version=v16.8.0`

feat(flex-linux-setup): application versions via arguments

---

flex-linux-setup/flex_linux_setup/flex_setup.py

fix(flex-linux-setup): jans-app-build

---

admin-ui/plugins/saml/components/TrustRelationForm.js

What is in the PR : 
==============
Fix the missing `email` attribute on the Released Attributes selection. by changing the limit search

fix(admin-ui): change max size of attribute results

---

admin-ui/app/locales/en/translation.json
admin-ui/plugins/auth-server/components/Configuration/JsonPropertyBuilder.js
admin-ui/plugins/auth-server/components/Ssa/CustomAttributesList.js
admin-ui/plugins/auth-server/components/Ssa/SsaAddPage.js
admin-ui/plugins/auth-server/components/Ssa/constants.js

What is in the PR : 
- Update SSA form input rules
- Add new input for SSA custom attributes
fix : #2006

fix(admin-ui): adding ssa custom attributes

---

charts/gluu/values.yaml

The changeset reverts default value to enable/disable saml and kc-scheduler.
Closes #2050

fix(charts): revert saml service to be disabled by default

---

automation/startflexdemo.sh
automation/startflexmonolithdemo.sh

The changeset removes unnecessary Python libs and add `PIP_BREAK_SYSTEM_PACKAGES` to address externally-managed-environment error while installing some libs not available in OS package manager.
Closes #2052

fix(cloud-native): demo scripts fail to deploy cluster due to python externally-managed-environment error

---

charts/gluu-all-in-one/templates/_helpers.tpl

The changeset fixes template loading when using Flex all-in-one chart and AWS as its configmap and secret storage.
Closes #2071

fix(charts): invalid template function calls when using AWS secrets manager

---

admin-ui/app/routes/Apps/Gluu/GluuAppSidebar.js
admin-ui/app/routes/Apps/Gluu/styles/GluuAppSidebar.style.js

This PR updates the Admin UI sidebar to conditionally hide optional components based on their installation status.
- SCIM and FIDO components will only be shown in the sidebar if their corresponding servers are installed and running.
- Improves the clarity and relevance of the sidebar by hiding components that are not part of the current Jans installation.
The sidebar now checks the status of SCIM and FIDO servers via the health API, and hides their menu entries if the servers are not installed or not running.
Closes #2087

feat(admin-ui): hide optional components from sidebar if not installed

---

admin-ui/plugins/auth-server/components/AuthN/index.js

This PR addresses a rendering failure causing a white screen on the AuthN page during load.
The AuthN component contained an unused Redux selector subscribing to a loading state from the Jans-Link plugin, which has been removed. This stale subscription triggered errors in the Redux state update cycle, preventing component render.
- Removed the obsolete "isLoading" state selector referencing Jans-Link from the AuthN component's Redux hooks.
AuthN page now successfully renders without interruption on load.
Closes #2093

fix(admin-ui): White screen on AuthN page load #2093

---

charts/gluu-all-in-one/templates/cronjobs.yaml
charts/gluu-all-in-one/values.yaml
charts/gluu/charts/auth-server-key-rotation/templates/cronjobs.yaml
charts/gluu/values.yaml

closes #2111 
allows to override the cron job schedule for the auth key rotation job via values.yaml

feat: add cronjob schedule override

---

docker-admin-ui/Dockerfile
docker-admin-ui/scripts/bootstrap.py
docker-admin-ui/templates/admin-ui/env-config.js

The changeset adds support for `AUTH_SERVER_HOSTNAME` env variable into admin-ui image.

feat(cloud-native): add server-hostname environment variable in admin-ui

---

docker-flex-monolith/.gitignore
docker-flex-monolith/Dockerfile

The changeset adds `apache2` package pre-installed during image build.
Closes #2171

chore(cloud-native): install apache2 package as part of monolith image build

---

admin-ui/app/locales/en/translation.json
admin-ui/app/locales/fr/translation.json
admin-ui/app/locales/pt/translation.json
admin-ui/plugins/auth-server/components/Configuration/ConfigPage.js
admin-ui/plugins/auth-server/components/Configuration/JsonPropertyBuilder.js

This PR updates the label in the Auth Server Properties screen to reflect a more accurate and standards-aligned description.
---
- Renamed label from **Discovery Deny Keys** to **OpenID Configuration Response OP Metadata Suppression List**.
- Improves clarity for users working with OpenID Connect server metadata suppression settings.
---
- No backend changes required — only a UI label update.
- Helps administrators better understand the purpose of this configuration field.
---
**Closes:** #2193  
**Title:** Change label in the Auth Server Properties

feat(admin-ui): update label in Auth Server Properties to match OP metadata context.
